---
title: "Proyecto Médodos II"
author: "Mauricio Caicedo Palacio - Fidela Makendengue"
date: "2022-01-30"
output:
  pdf_document: default
  html_document: default
editor_options:
  chunk_output_type: inline
---

# Introducción 

En el siguiente trabajo se hace un análisis de componentes principales, análisis factorial y análisis de comglomerados. Se considera la base de datos Heart Disease Diagnosis. Esta base de datos contiene 4 bases de datos relacionadas con el diagnóstico de enfermedades del corazón. Todos los atributos tienen valores numéricos. Los datos fueron recolectados de las cuatro ubicaciones siguientes:

-   Fundación de la Clínica Cleveland (cleveland.data)

-   Instituto Húngaro de Cardiología, Budapest (hungarian.data)

-   VA Centro médico, Long Beach, CA (long-beach-va.data)

-   Hospital Universitario, Zúrich, Suiza (switzerland.data)

En particular, nosotros utilizaremos la base de datos de Cleveland, donde la variable objetivo se refiere a la presencia de enfermedad cardíaca en el paciente. Tiene un valor entero de 0 a 4, donde cero es sin presencia de la enfermedad. Los experimentos con la base de datos de Cleveland se han concentrado simplemente en intentar distinguir la presencia (valores 1,2,3,4) de la ausencia (valor 0).

Las bases de datos tienen 76 atributos sin procesar, sin embargo solo se proporcionan 14 de ellos, cuando se descarga de la url, dado que estos son los que se utilizan para estudios relacionados con Machine Learning.

Los autores de las bases de datos son: 1. Instituto Húngaro de Cardiología. Budapest: Andras Janosi, MD 2. Hospital Universitario, Zúrich, Suiza: William Steinbrunn, M.D. 3. Hospital Universitario, Basilea, Suiza: Matthias Pfisterer, M.D. 4. VA Centro Médico, Long Beach y Fundación de la Clínica Cleveland: Robert Detrano, MD, Ph.D.

Finalmente, cabe mencionar que en este trabajo se presenta: un análisis previo, un análisis de componentes principales, un análisis factorial y un análisis de conglomerados.

# Análisis previo

## Resúmenes

Las bases de datos y la información relacionada con las mismas, se pueden encontrar en el siguiente enlace:

<https://archive.ics.uci.edu/ml/machine-learning-databases/heart-disease/>
