% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={Proyecto Médodos II},
  pdfauthor={Mauricio Caicedo Palacio - Fidela Makendengue},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Proyecto Médodos II}
\author{Mauricio Caicedo Palacio - Fidela Makendengue}
\date{2022-01-30}

\begin{document}
\maketitle

\hypertarget{introducciuxf3n}{%
\section{Introducción}\label{introducciuxf3n}}

En el siguiente trabajo se hace un análisis de componentes principales,
análisis factorial y análisis de conglomerados. Se considera la base de
datos Heart Disease Diagnosis. Esta base de datos contiene 4 bases de
datos relacionadas con el diagnóstico de enfermedades del corazón. Todos
los atributos tienen valores numéricos. Los datos fueron recolectados de
las cuatro ubicaciones siguientes:

\begin{itemize}
\item
  Fundación de la Clínica Cleveland (cleveland.data)
\item
  Instituto Húngaro de Cardiología, Budapest (hungarian.data)
\item
  VA Centro médico, Long Beach, CA (long-beach-va.data)
\item
  Hospital Universitario, Zúrich, Suiza (switzerland.data)
\end{itemize}

En particular, nosotros utilizaremos la base de datos de Cleveland,
donde la variable objetivo se refiere a la presencia de enfermedad
cardíaca en el paciente. Tiene un valor entero de 0 a 4, donde cero es
sin presencia de la enfermedad. Los experimentos con la base de datos de
Cleveland se han concentrado simplemente en intentar distinguir la
presencia (valores 1,2,3,4) de la ausencia (valor 0).

Las bases de datos tienen 76 atributos sin procesar, sin embargo solo se
proporcionan 14 de ellos, cuando se descarga de la url, dado que estos
son los que se utilizan para estudios relacionados con Machine Learning.

Los autores de las bases de datos son: 1. Instituto Húngaro de
Cardiologia. Budapest: Andras Janosi, MD 2. Hospital Universitario,
Zúrich, Suiza: William Steinbrunn, M.D.~3. Hospital Universitario,
Basilea, Suiza: Matthias Pfisterer, M.D.~4. VA Centro Médico, Long Beach
y Fundación de la Clínica Cleveland: Robert Detrano, MD, Ph.D.

Finalmente, cabe mencionar que en este trabajo se presenta: un análisis
previo, un análisis de componentes principales, un análisis factorial y
un análisis de conglomerados.

\hypertarget{anuxe1lisis-previo}{%
\section{Análisis previo}\label{anuxe1lisis-previo}}

\hypertarget{resuxfamenes}{%
\subsection{Resúmenes}\label{resuxfamenes}}

Las bases de datos y la información relacionada con las mismas, se
pueden encontrar en el siguiente enlace:

\url{https://archive.ics.uci.edu/ml/machine-learning-databases/heart-disease/}

Ahora bien, veamos la información de los nombres de los atributos o las
columnas:

1. age: edad en años.

2. sex: sexo (1 = masculino; 0 = femenino).

3. cp: tipo de dolor en el pecho -\/- Value 1: angina típica -\/- Value
2: angina atípica -\/- Value 3: dolor sin angina -\/- Value 4:
asintomático.

4. trestbps: presión arterial en reposo (en mm Hg al ingreso en el
hospital)

5. chol: colesterol sérico en mg/dl

6. fbs: (azúcar en sangre en ayunas \textbackslash\textgreater{} 120
mg/dl) (1 = verdadero; 0 = falso).

7. restecg: resultados electrocardiográficos en reposo -\/- Valor 0:
normal -\/- Valor 1: tener anormalidad de onda ST-T (inversiones de onda
T y/o ST elevación o depresión de \textbackslash\textgreater{} 0,05 mV)
-\/- Valor 2: mostrar hipertrofia ventricular izquierda probable o
definitiva según el criterio Estes

8. thalach: frecuencia cardíaca máxima alcanzada.

9. exang: angina inducida por el ejercicio (1 = sí; 0 = no).

10. oldpeak: Depresión del ST inducida por el ejercicio en relación con
el reposo.

11.slope: pendiente del segmento ST de ejercicio máximo -\/- Valor 1:
ascendente -\/- Valor 2: plano -\/- Valor 3: descendente.

12. ca: número de vasos principales (0-3) coloreados por fluoroscopia.

13. thal: 3 = normales; 6 = defecto fijo; 7 = defecto reversible.

14. num: diagnóstico de enfermedad cardíaca (estado de enfermedad
angiográfico) -\/- Valor 0: \textbackslash\textless{} 50\%
estrechamiento del diámetro -\/- Valor 1: \textbackslash\textgreater{}
50\% estrechamiento del diámetro (en cualquier vaso principal: los
atributos 59 a 68 son vasos).

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Cargamos las librerías que vamos a utilizar para todo el trabajo}
\FunctionTok{library}\NormalTok{(GGally)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Loading required package: ggplot2
\end{verbatim}

\begin{verbatim}
## Registered S3 method overwritten by 'GGally':
##   method from   
##   +.gg   ggplot2
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(ggplot2)}
\FunctionTok{library}\NormalTok{(DescTools)}
\FunctionTok{library}\NormalTok{(binom)}
\FunctionTok{library}\NormalTok{(nortest)}
\FunctionTok{library}\NormalTok{(stringr)}
\FunctionTok{library}\NormalTok{(NbClust)}
\FunctionTok{library}\NormalTok{(rgl)}
\FunctionTok{library}\NormalTok{(psych)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Attaching package: 'psych'
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:DescTools':
## 
##     AUC, ICC, SD
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:ggplot2':
## 
##     %+%, alpha
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(factoextra)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Welcome! Want to learn more? See two factoextra-related books at https://goo.gl/ve3WBa
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(caret)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Loading required package: lattice
\end{verbatim}

\begin{verbatim}
## 
## Attaching package: 'caret'
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:DescTools':
## 
##     MAE, RMSE
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(GGally)}
\FunctionTok{library}\NormalTok{(patchwork)}
\FunctionTok{library}\NormalTok{(Stat2Data)}
\FunctionTok{library}\NormalTok{(corrplot)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## corrplot 0.92 loaded
\end{verbatim}

Veamos una descripción sobre el conjunto de datos:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Cargamos los datos}
\NormalTok{data }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"https://archive.ics.uci.edu/ml/machine{-}learning{-}databases/heart{-}disease/processed.cleveland.data"}\NormalTok{,}\AttributeTok{sep =} \StringTok{","}\NormalTok{)}

\CommentTok{\#Cambiamos el nombre de las columnas }
\FunctionTok{colnames}\NormalTok{(data) }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{\textquotesingle{}age\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}sex\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}cp\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}trestbps\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}chol\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}fbs\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}restecg\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}thalach\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}exang\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}oldpeak\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}slope\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}ca\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}thal\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}num\textquotesingle{}}\NormalTok{)}

\CommentTok{\#Visualizamos las primeras 5 instancias de los datos.}
\FunctionTok{head}\NormalTok{(data,}\DecValTok{5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   age sex cp trestbps chol fbs restecg thalach exang oldpeak slope  ca thal num
## 1  67   1  4      160  286   0       2     108     1     1.5     2 3.0  3.0   2
## 2  67   1  4      120  229   0       2     129     1     2.6     2 2.0  7.0   1
## 3  37   1  3      130  250   0       0     187     0     3.5     3 0.0  3.0   0
## 4  41   0  2      130  204   0       2     172     0     1.4     1 0.0  3.0   0
## 5  56   1  2      120  236   0       0     178     0     0.8     1 0.0  3.0   0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{tail}\NormalTok{(data, }\DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     age sex cp trestbps chol fbs restecg thalach exang oldpeak slope  ca thal
## 300  57   1  4      130  131   0       0     115     1     1.2     2 1.0  7.0
## 301  57   0  2      130  236   0       2     174     0     0.0     2 1.0  3.0
## 302  38   1  3      138  175   0       0     173     0     0.0     1   ?  3.0
##     num
## 300   3
## 301   1
## 302   0
\end{verbatim}

En las visualizaciones de los datos se observan valores pequeños desde
0,1,2 hasta 250, 286, de acuerdo a las primeras tres filas.Como también
encontramos datos enteros y punto flotante. Veamos la dimensión del
conjunto de datos:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{dim}\NormalTok{(data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 302  14
\end{verbatim}

Este conjunto de datos contiene la información de 302 pacientes (302
instancias) basados en 14 atributos. A continuación, realizamos un breve
preprocesado de datos, para ello analizamos si el conjunto de datos
contiene datos nulos.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{any}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(data))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] FALSE
\end{verbatim}

En efecto, el conjunto de datos no contiene datos nulos, ahora bien,
vamos a hacer el estudio de los datos a nivel estadístico, y vamos a
denotar a la variable data\_num al conjunto de los datos numéricos sin
incluir las variables ca y thal, dado que son categóricas, de esta modo,
trabajamos sólo con 12 atributos.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Seleccionamos las variables numéricas sin la variable ca y thal}
\NormalTok{nums }\OtherTok{\textless{}{-}} \FunctionTok{unlist}\NormalTok{(}\FunctionTok{lapply}\NormalTok{(data, is.numeric), }\AttributeTok{use.names =} \ConstantTok{FALSE}\NormalTok{) }
\NormalTok{data\_num }\OtherTok{\textless{}{-}}\NormalTok{ data[ , nums]}
\FunctionTok{head}\NormalTok{(data\_num, }\DecValTok{5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   age sex cp trestbps chol fbs restecg thalach exang oldpeak slope num
## 1  67   1  4      160  286   0       2     108     1     1.5     2   2
## 2  67   1  4      120  229   0       2     129     1     2.6     2   1
## 3  37   1  3      130  250   0       0     187     0     3.5     3   0
## 4  41   0  2      130  204   0       2     172     0     1.4     1   0
## 5  56   1  2      120  236   0       0     178     0     0.8     1   0
\end{verbatim}

Resumen global del data frame.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{resumen }\OtherTok{\textless{}{-}} \FunctionTok{apply}\NormalTok{(data\_num, }\DecValTok{1}\NormalTok{,}
                     \ControlFlowTok{function}\NormalTok{(x) }\FunctionTok{c}\NormalTok{(}\FunctionTok{mean}\NormalTok{(x),}\FunctionTok{sd}\NormalTok{(x),}\FunctionTok{quantile}\NormalTok{(x)))}
\FunctionTok{rownames}\NormalTok{(resumen)}\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"Media"}\NormalTok{,}\StringTok{"DT"}\NormalTok{,}\StringTok{"Mínimo"}\NormalTok{,}\StringTok{"Q1"}\NormalTok{,}\StringTok{"Q2"}\NormalTok{,}\StringTok{"Q3"}\NormalTok{,}\StringTok{"Máximo"}\NormalTok{)}
\NormalTok{knitr}\SpecialCharTok{::}\FunctionTok{kable}\NormalTok{(resumen, }\AttributeTok{digits =} \DecValTok{5}\NormalTok{, }\AttributeTok{align =} \StringTok{"c"}\NormalTok{, }\AttributeTok{caption=}\StringTok{"Resumen global de las variables numéricas"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0021}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0027}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0030}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0030}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0030}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0030}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0030}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0030}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0030}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0030}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0030}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0030}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0030}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0030}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0030}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0030}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0030}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0030}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0030}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}
  >{\centering\arraybackslash}p{(\columnwidth - 604\tabcolsep) * \real{0.0033}}@{}}
\caption{Resumen global de las variables numéricas}\tabularnewline
\toprule()
\endhead
Media & 52.87500 & 46.55000 & 51.20833 & 46.11667 & 49.56667 & 53.80000
& 58.38333 & 50.53333 & 47.25833 & 45.36667 & 54.19167 & 49.71667 &
50.33333 & 49.29167 & 46.30000 & 46.91667 & 50.01667 & 49.68333 &
51.71667 & 44.81667 & 54.91667 & 52.650 & 50.01667 & 45.36667 & 46.13333
& 57.83333 & 46.88333 & 51.54167 & 37.16667 & 50.23333 & 48.20000 &
58.58333 & 49.70833 & 49.36667 & 49.33333 & 39.62500 & 50.55000 &
57.01667 & 50.00000 & 47.25000 & 46.86667 & 58.20000 & 48.80000 &
58.16667 & 48.29167 & 38.71667 & 48.88333 & 65.56667 & 45.26667 &
42.91667 & 42.36667 & 50.75000 & 48.91667 & 49.7000 & 47.18333 &
49.46667 & 40.83333 & 51.12500 & 43.45000 & 53.18333 & 44.61667 &
45.51667 & 55.66667 & 40.45000 & 53.65000 & 46.00000 & 50.80000 &
59.28333 & 48.71667 & 53.48333 & 51.68333 & 46.56667 & 49.21667 &
44.75000 & 61.9000 & 49.81667 & 54.04167 & 50.85000 & 50.15000 &
43.16667 & 49.86667 & 57.41667 & 57.21667 & 56.1000 & 50.50000 &
50.41667 & 43.16667 & 49.33333 & 49.37500 & 54.03333 & 45.76667 &
48.06667 & 39.46667 & 52.33333 & 50.33333 & 46.93333 & 53.21667 &
45.81667 & 48.83333 & 51.08333 & 42.7500 & 54.5000 & 48.58333 & 42.25000
& 52.58333 & 45.58333 & 47.78333 & 49.55000 & 43.93333 & 55.83333 &
48.93333 & 46.0000 & 55.58333 & 46.68333 & 43.00000 & 48.50000 &
45.36667 & 55.81667 & 49.56667 & 49.75000 & 65.83333 & 43.68333 &
45.05000 & 55.70000 & 49.21667 & 57.91667 & 45.23333 & 46.50000 &
46.91667 & 48.95000 & 44.33333 & 47.58333 & 53.91667 & 45.68333 &
50.70000 & 44.13333 & 48.11667 & 41.13333 & 49.86667 & 49.08333 &
56.93333 & 47.83333 & 53.23333 & 47.21667 & 46.33333 & 54.16667 &
48.91667 & 54.75000 & 53.66667 & 57.18333 & 44.96667 & 76.21667 &
55.31667 & 45.18333 & 53.61667 & 56.05000 & 55.25000 & 56.26667 &
51.66667 & 42.08333 & 56.75000 & 45.21667 & 44.75000 & 50.66667 &
47.58333 & 48.91667 & 53.33333 & 50.75000 & 38.25000 & 51.99167 &
45.08333 & 52.75000 & 63.51667 & 47.33333 & 48.43333 & 45.59167 &
40.84167 & 54.74167 & 50.83333 & 52.04167 & 63.49167 & 51.48333 &
55.26667 & 57.66667 & 48.33333 & 50.40000 & 50.0000 & 60.91667 &
51.75000 & 45.25000 & 52.18333 & 48.09167 & 50.90833 & 43.54167 &
50.40833 & 50.09167 & 48.35000 & 48.34167 & 51.91667 & 48.33333 &
60.7500 & 42.68333 & 54.51667 & 44.25000 & 54.66667 & 49.25000 &
44.49167 & 50.50000 & 51.61667 & 45.50000 & 48.65000 & 46.91667 &
54.08333 & 46.7500 & 44.90833 & 44.16667 & 49.00000 & 52.25000 &
54.83333 & 50.00000 & 50.16667 & 42.91667 & 47.16667 & 51.56667 &
46.47500 & 42.6750 & 56.00000 & 40.91667 & 44.42500 & 46.6750 & 57.7000
& 37.56667 & 49.18333 & 48.50000 & 49.51667 & 48.96667 & 47.40000 &
51.66667 & 51.91667 & 45.25000 & 53.25000 & 51.33333 & 48.55000 &
38.25000 & 42.08333 & 46.34167 & 46.83333 & 47.25000 & 45.41667 &
41.95833 & 44.7500 & 47.35000 & 52.46667 & 54.18333 & 45.75000 & 45.2750
& 44.67500 & 51.66667 & 49.02500 & 46.5250 & 56.16667 & 51.99167 &
47.00000 & 42.30000 & 52.48333 & 46.00000 & 45.68333 & 50.25000 &
42.25000 & 46.49167 & 50.19167 & 52.40000 & 38.71667 & 46.98333 &
51.88333 & 54.08333 & 46.16667 & 51.16667 & 43.5500 & 54.83333 &
51.16667 & 44.25000 & 43.91667 & 48.41667 & 53.95000 & 51.15000 &
46.03333 & 48.00000 & 49.25000 & 49.23333 & 58.26667 & 40.90000 &
45.7500 & 44.00000 & 42.00000 & 41.91667 & 47.43333 & 46.43333 &
46.61667 & 37.10000 & 50.33333 & 44.08333 \\
DT & 90.46951 & 75.07689 & 87.54310 & 76.43833 & 82.81435 & 88.51588 &
108.14510 & 83.32933 & 74.39783 & 71.94730 & 94.07630 & 83.17528 &
87.92490 & 79.19437 & 72.94972 & 79.01146 & 82.70233 & 87.66612 &
89.03983 & 72.21485 & 93.42713 & 90.841 & 80.28769 & 71.16571 & 76.45625
& 105.66743 & 76.61486 & 86.72880 & 58.81223 & 82.02416 & 78.58758 &
104.32158 & 81.32607 & 83.08448 & 82.53741 & 62.65168 & 87.29924 &
105.96039 & 82.05098 & 76.03603 & 77.53776 & 98.83286 & 78.05085 &
103.35449 & 78.67553 & 62.14250 & 80.79480 & 124.60512 & 72.02183 &
72.63665 & 66.08049 & 91.00862 & 81.70730 & 82.9161 & 82.15597 &
81.80350 & 66.29388 & 87.81803 & 71.71606 & 94.76039 & 70.93287 &
73.07259 & 97.83226 & 64.54141 & 90.35836 & 71.40537 & 82.85523 &
102.74832 & 80.41608 & 89.54432 & 84.83998 & 81.65269 & 81.88073 &
73.95714 & 111.2987 & 83.07961 & 96.38900 & 85.60659 & 85.77845 &
71.14880 & 85.30051 & 103.45878 & 93.10141 & 102.0483 & 84.51627 &
85.89154 & 71.81268 & 81.47764 & 84.20622 & 94.26797 & 68.95742 &
78.45867 & 64.26362 & 86.56614 & 85.09496 & 77.73182 & 87.05724 &
74.37108 & 81.16967 & 88.30882 & 71.7041 & 95.8697 & 83.09738 & 67.46868
& 95.92749 & 71.18664 & 78.15730 & 83.06489 & 73.77841 & 96.73284 &
81.34874 & 75.0406 & 103.13932 & 81.56895 & 71.57958 & 77.75194 &
75.19873 & 99.92872 & 81.82553 & 83.97632 & 122.05873 & 73.51663 &
72.45584 & 93.34836 & 82.71034 & 97.03463 & 75.97798 & 78.44801 &
75.72253 & 83.53221 & 75.74399 & 81.46439 & 90.48200 & 76.45345 &
84.65925 & 66.40287 & 85.30981 & 68.39135 & 83.11632 & 79.72391 &
96.16283 & 78.34636 & 94.56926 & 79.18413 & 79.92989 & 92.54270 &
85.31381 & 98.26321 & 98.24675 & 98.65700 & 81.48472 & 162.85013 &
93.66014 & 76.14247 & 96.71880 & 97.16637 & 96.11652 & 95.34063 &
88.44961 & 70.20549 & 96.10896 & 74.62451 & 77.31062 & 86.62178 &
76.63071 & 80.52945 & 92.65904 & 90.49272 & 61.54396 & 86.86448 &
75.07749 & 86.77989 & 118.68294 & 74.25305 & 85.83705 & 77.07246 &
64.28340 & 99.21181 & 84.83228 & 89.36454 & 121.55482 & 86.91126 &
91.68612 & 98.91533 & 77.22851 & 85.77917 & 82.5095 & 101.52246 &
84.25192 & 73.58746 & 92.07726 & 81.46684 & 90.19610 & 70.09003 &
89.97919 & 81.00444 & 80.81481 & 82.37564 & 88.88139 & 83.33103 &
105.1269 & 67.21988 & 97.09379 & 74.41423 & 96.97829 & 82.38835 &
70.96331 & 86.33813 & 84.01764 & 77.49545 & 82.00032 & 77.58217 &
85.37666 & 78.3583 & 71.88470 & 74.42975 & 82.31094 & 92.90868 &
91.96426 & 88.23934 & 87.16320 & 73.79758 & 85.18732 & 87.73451 &
79.84666 & 70.6992 & 93.55795 & 66.78386 & 71.10303 & 75.1068 & 102.7482
& 58.37464 & 84.13195 & 78.20079 & 87.21678 & 86.33958 & 81.08106 &
89.45119 & 93.95111 & 78.53792 & 97.11298 & 88.74205 & 79.30925 &
61.31458 & 73.15793 & 77.87368 & 83.97276 & 76.71331 & 72.83288 &
67.77250 & 73.3759 & 81.90447 & 93.25251 & 97.43830 & 76.67538 & 74.4905
& 69.87388 & 84.03823 & 84.09555 & 80.1494 & 99.49311 & 85.54967 &
79.47327 & 63.62495 & 96.33523 & 73.65522 & 73.74233 & 83.61832 &
68.85707 & 73.42523 & 80.21610 & 95.30674 & 58.34521 & 75.56601 &
83.26180 & 90.94300 & 77.75583 & 83.27374 & 69.7366 & 100.89493 &
87.25806 & 70.62851 & 73.92313 & 76.66154 & 96.39838 & 81.37845 &
75.50156 & 78.51346 & 82.35414 & 77.44182 & 106.27383 & 64.38388 &
70.1947 & 69.70066 & 69.21114 & 66.33586 & 79.24759 & 82.78163 &
71.63683 & 55.63723 & 82.97462 & 72.44617 \\
Mínimo & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 &
0.00000 & 0.00000 & 1.00000 & 0.00000 & 0.00000 & 0.60000 & 0.00000 &
0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 &
0.00000 & 0.000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 &
0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 &
0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 &
0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 &
0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.0000 & 0.00000 &
0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 &
0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 &
0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.0000 & 0.00000 &
0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 1.00000 &
0.0000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 &
0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 &
0.00000 & 0.00000 & 0.00000 & 0.0000 & 0.0000 & 0.00000 & 0.00000 &
0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 1.00000 &
0.0000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 1.00000 &
0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 &
0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 &
0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 &
0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 &
0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 &
0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 &
0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 &
0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 &
0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 &
0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.0000 & 0.00000 &
0.00000 & 0.00000 & 0.00000 & 0.10000 & 0.00000 & 0.00000 & 0.00000 &
0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.0000 & 0.00000 &
0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 &
0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.0000 & 0.00000 & 0.00000 &
0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 &
0.00000 & 0.00000 & 0.0000 & 0.00000 & 0.00000 & 0.00000 & 0.0000 &
0.0000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 1.00000 & 0.00000 &
0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 &
0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.0000 &
0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.0000 & 0.00000 & 0.00000 &
0.00000 & 0.0000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 &
0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 &
0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.0000 &
0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 &
0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.0000 &
0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 &
0.00000 & 0.00000 \\
Q1 & 1.37500 & 1.00000 & 0.00000 & 0.00000 & 0.00000 & 1.50000 & 0.00000
& 1.30000 & 1.00000 & 0.00000 & 0.00000 & 1.00000 & 0.00000 & 0.37500 &
0.00000 & 0.75000 & 0.00000 & 0.00000 & 0.00000 & 1.00000 & 0.75000 &
1.000 & 1.00000 & 1.75000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 &
1.75000 & 0.00000 & 1.00000 & 0.00000 & 0.00000 & 0.30000 & 0.00000 &
1.75000 & 1.00000 & 1.00000 & 1.00000 & 0.75000 & 0.75000 & 0.00000 &
0.75000 & 0.00000 & 1.75000 & 0.00000 & 1.75000 & 0.60000 & 1.00000 &
0.00000 & 0.00000 & 0.75000 & 0.00000 & 1.0000 & 1.00000 & 0.45000 &
0.75000 & 0.37500 & 1.00000 & 0.75000 & 0.75000 & 1.00000 & 0.00000 &
0.75000 & 1.75000 & 1.00000 & 0.75000 & 1.75000 & 0.75000 & 0.00000 &
0.80000 & 1.00000 & 0.90000 & 0.75000 & 0.0000 & 1.00000 & 0.00000 &
0.15000 & 1.00000 & 1.00000 & 0.00000 & 0.00000 & 1.45000 & 0.0000 &
0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.30000 & 1.50000 &
0.00000 & 0.00000 & 0.00000 & 0.75000 & 1.15000 & 1.50000 & 0.00000 &
0.00000 & 0.00000 & 0.0000 & 0.0000 & 0.00000 & 0.75000 & 0.00000 &
0.75000 & 0.85000 & 1.00000 & 0.75000 & 1.00000 & 1.00000 & 0.0000 &
1.75000 & 0.00000 & 0.00000 & 0.75000 & 0.00000 & 1.00000 & 1.75000 &
1.00000 & 1.50000 & 0.75000 & 1.00000 & 1.00000 & 0.00000 & 1.75000 &
1.00000 & 0.00000 & 0.00000 & 0.30000 & 0.00000 & 0.00000 & 0.75000 &
0.00000 & 0.00000 & 1.00000 & 1.30000 & 1.00000 & 1.00000 & 0.00000 &
0.80000 & 0.00000 & 1.00000 & 0.90000 & 0.00000 & 1.00000 & 0.00000 &
0.00000 & 0.00000 & 0.75000 & 0.00000 & 0.00000 & 1.00000 & 1.75000 &
1.00000 & 1.00000 & 0.75000 & 1.15000 & 0.00000 & 0.00000 & 1.00000 &
0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.75000 & 1.00000 &
0.00000 & 1.00000 & 0.75000 & 0.00000 & 0.00000 & 1.75000 & 1.00000 &
0.07500 & 1.00000 & 0.00000 & 0.75000 & 0.87500 & 1.67500 & 0.60000 &
0.75000 & 0.00000 & 0.00000 & 0.60000 & 0.7500 & 0.75000 & 1.75000 &
0.00000 & 1.00000 & 1.00000 & 0.75000 & 0.00000 & 1.00000 & 0.77500 &
0.15000 & 0.00000 & 0.75000 & 0.00000 & 0.0000 & 0.15000 & 0.00000 &
0.00000 & 1.00000 & 1.75000 & 1.00000 & 0.00000 & 0.75000 & 0.00000 &
1.00000 & 0.75000 & 1.00000 & 0.0000 & 0.75000 & 0.00000 & 0.00000 &
0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.00000 & 1.00000 & 0.75000 &
0.00000 & 0.0000 & 0.00000 & 1.00000 & 1.00000 & 0.0000 & 1.0000 &
0.95000 & 0.15000 & 0.00000 & 1.75000 & 1.45000 & 0.95000 & 0.00000 &
0.00000 & 0.00000 & 0.00000 & 0.00000 & 0.75000 & 0.00000 & 0.75000 &
0.07500 & 1.00000 & 0.75000 & 0.75000 & 0.75000 & 0.7500 & 0.15000 &
0.00000 & 0.00000 & 0.00000 & 0.0000 & 0.00000 & 0.00000 & 0.22500 &
0.0000 & 0.75000 & 0.00000 & 0.00000 & 1.75000 & 1.00000 & 1.00000 &
1.00000 & 0.00000 & 0.00000 & 1.00000 & 0.75000 & 1.00000 & 0.00000 &
0.60000 & 0.45000 & 0.00000 & 0.00000 & 0.75000 & 0.0000 & 1.00000 &
0.00000 & 1.00000 & 0.00000 & 0.00000 & 1.00000 & 1.75000 & 0.00000 &
0.00000 & 0.00000 & 0.95000 & 0.00000 & 1.00000 & 1.0000 & 0.00000 &
0.00000 & 1.00000 & 0.15000 & 0.75000 & 1.00000 & 1.00000 & 0.00000 &
0.00000 \\
Q2 & 2.00000 & 2.30000 & 3.00000 & 1.70000 & 1.00000 & 3.30000 & 1.00000
& 2.00000 & 3.05000 & 1.50000 & 2.00000 & 2.00000 & 1.00000 & 1.00000 &
1.30000 & 1.50000 & 1.10000 & 0.60000 & 1.00000 & 1.90000 & 1.00000 &
2.000 & 3.00000 & 3.20000 & 1.80000 & 0.50000 & 1.80000 & 1.25000 &
2.50000 & 1.00000 & 1.70000 & 1.00000 & 1.50000 & 1.00000 & 1.00000 &
2.75000 & 2.00000 & 2.50000 & 1.50000 & 3.00000 & 1.00000 & 0.70000 &
1.30000 & 1.50000 & 2.75000 & 1.00000 & 3.30000 & 1.50000 & 2.50000 &
0.50000 & 1.00000 & 2.00000 & 1.50000 & 1.2000 & 2.10000 & 1.50000 &
1.50000 & 2.50000 & 1.20000 & 2.00000 & 2.50000 & 2.10000 & 1.00000 &
2.00000 & 2.40000 & 2.50000 & 1.80000 & 3.20000 & 2.50000 & 0.90000 &
2.50000 & 1.90000 & 1.50000 & 1.50000 & 1.5000 & 2.40000 & 1.75000 &
2.00000 & 2.50000 & 2.50000 & 2.00000 & 1.50000 & 2.50000 & 1.0000 &
1.50000 & 1.50000 & 1.50000 & 1.50000 & 1.50000 & 2.00000 & 3.50000 &
1.90000 & 1.30000 & 1.50000 & 1.00000 & 2.00000 & 2.80000 & 1.00000 &
1.50000 & 1.50000 & 1.0000 & 1.5000 & 1.50000 & 2.50000 & 1.00000 &
1.50000 & 2.00000 & 2.80000 & 2.50000 & 2.00000 & 2.00000 & 1.5000 &
2.50000 & 2.00000 & 1.50000 & 1.50000 & 1.20000 & 2.50000 & 2.40000 &
2.50000 & 4.00000 & 1.60000 & 3.50000 & 1.70000 & 2.00000 & 3.50000 &
2.90000 & 1.00000 & 0.50000 & 2.00000 & 1.00000 & 1.50000 & 1.50000 &
1.10000 & 2.00000 & 3.50000 & 2.00000 & 1.80000 & 2.20000 & 1.00000 &
1.50000 & 1.00000 & 1.90000 & 2.00000 & 1.00000 & 3.00000 & 1.00000 &
1.50000 & 0.50000 & 1.10000 & 2.00000 & 2.00000 & 3.00000 & 3.00000 &
2.20000 & 1.30000 & 1.50000 & 2.00000 & 1.00000 & 1.00000 & 3.00000 &
1.80000 & 2.00000 & 1.00000 & 1.00000 & 1.00000 & 1.50000 & 1.50000 &
1.00000 & 2.95000 & 1.50000 & 1.50000 & 2.00000 & 3.00000 & 1.60000 &
1.00000 & 2.05000 & 1.45000 & 1.50000 & 2.50000 & 2.00000 & 1.00000 &
2.50000 & 1.50000 & 0.50000 & 2.00000 & 2.0000 & 1.50000 & 2.00000 &
1.00000 & 3.50000 & 2.00000 & 2.00000 & 2.00000 & 2.50000 & 1.50000 &
2.00000 & 1.05000 & 1.00000 & 1.50000 & 1.0000 & 1.00000 & 0.60000 &
1.00000 & 2.50000 & 3.00000 & 2.50000 & 1.00000 & 1.70000 & 0.50000 &
2.90000 & 2.00000 & 2.50000 & 1.0000 & 1.95000 & 0.50000 & 2.00000 &
2.00000 & 1.50000 & 1.50000 & 1.50000 & 0.50000 & 2.50000 & 1.90000 &
0.85000 & 1.0000 & 0.50000 & 2.50000 & 2.00000 & 2.0000 & 2.7000 &
1.50000 & 1.50000 & 0.50000 & 3.10000 & 2.50000 & 1.50000 & 1.00000 &
1.00000 & 1.00000 & 0.50000 & 0.50000 & 2.00000 & 1.00000 & 2.00000 &
1.50000 & 2.00000 & 2.00000 & 1.50000 & 1.75000 & 2.0000 & 1.50000 &
1.50000 & 1.60000 & 1.00000 & 0.6500 & 1.55000 & 1.50000 & 1.00000 &
1.1500 & 2.00000 & 0.95000 & 1.00000 & 3.80000 & 2.00000 & 2.00000 &
2.10000 & 1.00000 & 1.00000 & 1.95000 & 2.15000 & 2.00000 & 1.80000 &
1.00000 & 1.50000 & 2.00000 & 1.00000 & 1.50000 & 1.3000 & 2.50000 &
1.00000 & 2.50000 & 1.00000 & 1.50000 & 4.00000 & 2.40000 & 1.50000 &
1.50000 & 1.50000 & 2.00000 & 1.10000 & 2.90000 & 3.0000 & 1.50000 &
1.00000 & 2.50000 & 1.50000 & 1.10000 & 2.70000 & 2.50000 & 2.00000 &
1.00000 \\
Q3 & 77.25000 & 80.25000 & 60.25000 & 63.25000 & 72.00000 & 81.50000 &
72.75000 & 79.75000 & 74.75000 & 77.75000 & 77.00000 & 74.50000 &
63.00000 & 79.50000 & 80.25000 & 63.50000 & 75.50000 & 68.50000 &
69.25000 & 75.50000 & 81.00000 & 73.500 & 76.50000 & 77.50000 & 67.50000
& 73.50000 & 78.00000 & 69.75000 & 57.50000 & 86.75000 & 74.25000 &
83.00000 & 78.00000 & 65.50000 & 66.50000 & 62.25000 & 70.75000 &
74.25000 & 80.00000 & 77.25000 & 65.00000 & 93.25000 & 81.75000 &
78.25000 & 71.50000 & 65.75000 & 69.50000 & 83.75000 & 72.25000 &
57.00000 & 78.75000 & 61.00000 & 65.50000 & 77.5000 & 67.75000 &
72.50000 & 58.25000 & 71.75000 & 69.50000 & 70.75000 & 70.00000 &
75.50000 & 74.25000 & 68.75000 & 80.50000 & 80.00000 & 78.00000 &
79.25000 & 71.25000 & 85.75000 & 81.50000 & 71.25000 & 76.25000 &
60.50000 & 86.5000 & 76.25000 & 73.25000 & 68.50000 & 71.25000 &
59.75000 & 72.25000 & 64.25000 & 88.50000 & 69.0000 & 68.00000 &
69.75000 & 68.50000 & 74.25000 & 70.75000 & 79.50000 & 82.75000 &
79.00000 & 60.00000 & 81.00000 & 71.00000 & 71.75000 & 82.50000 &
72.50000 & 66.50000 & 62.50000 & 55.0000 & 74.7500 & 80.75000 & 66.75000
& 67.50000 & 79.25000 & 74.75000 & 75.75000 & 58.75000 & 82.00000 &
73.25000 & 68.5000 & 65.25000 & 70.75000 & 63.75000 & 78.50000 &
60.75000 & 79.75000 & 80.50000 & 68.50000 & 84.75000 & 63.25000 &
69.00000 & 83.25000 & 66.25000 & 75.25000 & 68.00000 & 63.00000 &
77.50000 & 70.50000 & 61.75000 & 54.25000 & 73.25000 & 62.75000 &
75.00000 & 83.75000 & 72.25000 & 56.25000 & 69.50000 & 79.25000 &
84.00000 & 71.00000 & 79.25000 & 69.75000 & 62.25000 & 73.75000 &
58.75000 & 65.75000 & 70.50000 & 77.00000 & 57.00000 & 79.00000 &
77.50000 & 72.00000 & 79.75000 & 73.25000 & 74.75000 & 80.00000 &
80.50000 & 59.75000 & 89.00000 & 68.00000 & 68.50000 & 67.00000 &
75.75000 & 73.50000 & 73.50000 & 57.75000 & 61.75000 & 80.50000 &
67.50000 & 80.00000 & 81.50000 & 81.00000 & 64.75000 & 66.00000 &
68.25000 & 64.75000 & 72.25000 & 67.00000 & 75.50000 & 68.50000 &
80.50000 & 84.50000 & 82.25000 & 61.50000 & 79.5000 & 88.50000 &
86.75000 & 69.75000 & 68.75000 & 65.25000 & 73.00000 & 79.75000 &
75.25000 & 84.50000 & 68.25000 & 67.50000 & 75.50000 & 65.00000 &
86.5000 & 74.25000 & 81.25000 & 59.75000 & 69.25000 & 75.50000 &
69.00000 & 73.75000 & 84.00000 & 57.75000 & 58.50000 & 63.25000 &
90.75000 & 67.0000 & 72.00000 & 60.75000 & 69.00000 & 78.50000 &
78.75000 & 58.75000 & 67.50000 & 52.75000 & 63.50000 & 74.25000 &
55.00000 & 63.2500 & 88.25000 & 67.50000 & 77.50000 & 73.0000 & 70.5000
& 66.25000 & 85.50000 & 80.50000 & 69.50000 & 67.75000 & 64.50000 &
70.25000 & 61.50000 & 58.25000 & 62.25000 & 69.25000 & 79.25000 &
69.00000 & 68.00000 & 68.50000 & 62.75000 & 70.25000 & 78.50000 &
70.25000 & 69.7500 & 74.25000 & 68.25000 & 61.00000 & 61.50000 & 76.7500
& 86.00000 & 88.25000 & 73.75000 & 62.5000 & 77.50000 & 82.50000 &
63.00000 & 77.00000 & 62.75000 & 71.00000 & 75.75000 & 68.00000 &
64.00000 & 80.25000 & 84.00000 & 64.50000 & 81.25000 & 77.75000 &
86.75000 & 86.00000 & 63.75000 & 81.25000 & 76.0000 & 70.25000 &
67.75000 & 73.25000 & 56.75000 & 82.75000 & 72.00000 & 80.00000 &
74.75000 & 74.50000 & 72.00000 & 87.75000 & 74.25000 & 63.00000 &
82.2500 & 78.25000 & 60.75000 & 66.75000 & 73.50000 & 61.25000 &
86.25000 & 71.50000 & 75.25000 & 63.00000 \\
Máximo & 286.00000 & 229.00000 & 250.00000 & 204.00000 & 236.00000 &
268.00000 & 354.00000 & 254.00000 & 203.00000 & 192.00000 & 294.00000 &
256.00000 & 263.00000 & 199.00000 & 174.00000 & 229.00000 & 239.00000 &
275.00000 & 266.00000 & 211.00000 & 283.00000 & 284.000 & 224.00000 &
206.00000 & 219.00000 & 340.00000 & 226.00000 & 247.00000 & 167.00000 &
239.00000 & 230.00000 & 335.00000 & 234.00000 & 233.00000 & 226.00000 &
177.00000 & 276.00000 & 353.00000 & 243.00000 & 225.00000 & 199.00000 &
302.00000 & 212.00000 & 330.00000 & 230.00000 & 175.00000 & 243.00000 &
417.00000 & 197.00000 & 198.00000 & 177.00000 & 290.00000 & 219.00000 &
253.0000 & 266.00000 & 233.00000 & 172.00000 & 273.00000 & 213.00000 &
305.00000 & 177.00000 & 216.00000 & 304.00000 & 188.00000 & 282.00000 &
185.00000 & 232.00000 & 326.00000 & 231.00000 & 269.00000 & 254.00000 &
267.00000 & 248.00000 & 197.00000 & 360.0000 & 258.00000 & 308.00000 &
245.00000 & 270.00000 & 208.00000 & 264.00000 & 321.00000 & 274.00000 &
325.0000 & 235.00000 & 257.00000 & 216.00000 & 234.00000 & 256.00000 &
302.00000 & 164.00000 & 231.00000 & 175.00000 & 252.00000 & 255.00000 &
239.00000 & 258.00000 & 201.00000 & 222.00000 & 260.00000 & 182.0000 &
303.0000 & 265.00000 & 188.00000 & 309.00000 & 177.00000 & 229.00000 &
260.00000 & 219.00000 & 307.00000 & 249.00000 & 190.0000 & 341.00000 &
263.00000 & 203.00000 & 211.00000 & 183.00000 & 330.00000 & 254.00000 &
256.00000 & 407.00000 & 222.00000 & 217.00000 & 282.00000 & 234.00000 &
288.00000 & 239.00000 & 220.00000 & 209.00000 & 258.00000 & 227.00000 &
204.00000 & 261.00000 & 213.00000 & 250.00000 & 174.00000 & 281.00000 &
198.00000 & 245.00000 & 221.00000 & 288.00000 & 205.00000 & 309.00000 &
240.00000 & 243.00000 & 289.00000 & 250.00000 & 308.00000 & 318.00000 &
298.00000 & 265.00000 & 564.00000 & 289.00000 & 246.00000 & 322.00000 &
299.00000 & 300.00000 & 293.00000 & 277.00000 & 197.00000 & 304.00000 &
214.00000 & 248.00000 & 255.00000 & 207.00000 & 223.00000 & 288.00000 &
282.00000 & 160.00000 & 269.00000 & 226.00000 & 249.00000 & 394.00000 &
212.00000 & 274.00000 & 233.00000 & 184.00000 & 315.00000 & 246.00000 &
274.00000 & 409.00000 & 244.00000 & 270.00000 & 305.00000 & 195.00000 &
240.00000 & 246.0000 & 283.00000 & 254.00000 & 196.00000 & 298.00000 &
247.00000 & 294.00000 & 211.00000 & 299.00000 & 234.00000 & 236.00000 &
244.00000 & 273.00000 & 254.00000 & 325.0000 & 173.00000 & 313.00000 &
211.00000 & 309.00000 & 259.00000 & 200.00000 & 262.00000 & 244.00000 &
215.00000 & 231.00000 & 214.00000 & 228.00000 & 230.0000 & 193.00000 &
204.00000 & 243.00000 & 303.00000 & 271.00000 & 268.00000 & 267.00000 &
199.00000 & 282.00000 & 269.00000 & 210.00000 & 204.0000 & 277.00000 &
206.00000 & 212.00000 & 196.0000 & 327.0000 & 149.00000 & 269.00000 &
201.00000 & 286.00000 & 283.00000 & 249.00000 & 271.00000 & 295.00000 &
235.00000 & 306.00000 & 269.00000 & 234.00000 & 178.00000 & 237.00000 &
234.00000 & 275.00000 & 212.00000 & 208.00000 & 201.00000 & 218.0000 &
263.00000 & 295.00000 & 303.00000 & 209.00000 & 223.0000 & 197.00000 &
245.00000 & 261.00000 & 242.0000 & 319.00000 & 240.00000 & 226.00000 &
166.00000 & 315.00000 & 204.00000 & 218.00000 & 223.00000 & 180.00000 &
207.00000 & 228.00000 & 311.00000 & 149.00000 & 204.00000 & 227.00000 &
278.00000 & 220.00000 & 232.00000 & 197.0000 & 335.00000 & 253.00000 &
205.00000 & 192.00000 & 203.00000 & 318.00000 & 225.00000 & 220.00000 &
221.00000 & 240.00000 & 212.00000 & 342.00000 & 169.00000 & 187.0000 &
197.00000 & 182.00000 & 176.00000 & 241.00000 & 264.00000 & 193.00000 &
131.00000 & 236.00000 & 175.00000 \\
\bottomrule()
\end{longtable}

\hypertarget{visualizaciuxf3n}{%
\subsection{Visualización}\label{visualizaciuxf3n}}

En la siguiente sección, realizamos algunas gráficas para determinar
relaciones entre las variables, distribuciones de los datos, entre otras
características que iremos detallando. También, usaremos la notación HDD
para denotar el conjunto de datos Heart Disease Diagnosis.

El primero es el gráfico de correlaciones

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Gráfico de correlaciones}
\NormalTok{title }\OtherTok{\textless{}{-}} \StringTok{"Correlaciones entre las variables de HDD"}
\CommentTok{\#Matriz de correlaciones}
\NormalTok{M }\OtherTok{\textless{}{-}} \FunctionTok{cor}\NormalTok{(data\_num)}
\FunctionTok{corrplot}\NormalTok{(M, }\AttributeTok{col =} \FunctionTok{COL2}\NormalTok{(}\StringTok{\textquotesingle{}RdYlBu\textquotesingle{}}\NormalTok{), }\AttributeTok{addCoef.col =} \StringTok{\textquotesingle{}black\textquotesingle{}}\NormalTok{, }\AttributeTok{tl.pos =} \StringTok{\textquotesingle{}d\textquotesingle{}}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{methods-II_files/figure-latex/unnamed-chunk-8-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{corPlot}\NormalTok{(data\_num, }\AttributeTok{min.length =} \DecValTok{9}\NormalTok{, }\AttributeTok{cex =} \FloatTok{0.5}\NormalTok{, }\AttributeTok{alpha =} \FloatTok{0.8}\NormalTok{, }\AttributeTok{colors =} \ConstantTok{TRUE}\NormalTok{ )}
\end{Highlighting}
\end{Shaded}

\includegraphics{methods-II_files/figure-latex/unnamed-chunk-9-1.pdf}

Para comprender el gráfico de correlaciones, debemos tener en cuenta que
si, el valor que toma es 1, quiere decir que las variables están
completamente relacionadas, además el color azul más fuerte significa lo
mismo, en tonalidades más claras tenemos una relación menor. Por otro
lado, diremos que dos variables no están relacionadas cuando toman
valores de -1, también el color rojo representa que no hay relación
entre estas variables, donde el rojo más claro como rosa determina un
leve incremento de la relación. El color blanco, cuyo valor asociado es
el cero, indica que hay un 50\% de relación entre las variables. Algunas
inferencias del gráfico anterior son:

1. Las variables que están 100\% relacionadas son cada una con ella
misma.

2. Las variables más relacionadas son: slope con oldpeak (0.58), num con
oldpeak(0.51), num con cp (0.41), num con slope (0.39), exang con cop
(0.38).

3. Las variables menos relacionadas son: thalac con num (-42), thalac
con age (-0.39), thalac con slope (-0.39), thalac con exang (-0.38),
thalach con oldpeak (-0.34), thalac con oldpeak (-0.34).

4. La variable thalac es la que está menos relacionada con las
variables: num, slope, oldpeak, exang, age, cp.~Podemos pensar en
eliminar esta variable del conjunto de datos.

Como consecuencia, se elimina la variable thalac y seguimos el estudio
con 11 atributos.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Seleccionamos las variables numéricas sin la variable ca, thal y thalac}

\NormalTok{data\_num }\OtherTok{\textless{}{-}}\NormalTok{ data\_num[,}\SpecialCharTok{{-}}\DecValTok{8}\NormalTok{] }\CommentTok{\# 8 es el índice de la variable thalac}
\FunctionTok{head}\NormalTok{(data\_num, }\DecValTok{4}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   age sex cp trestbps chol fbs restecg exang oldpeak slope num
## 1  67   1  4      160  286   0       2     1     1.5     2   2
## 2  67   1  4      120  229   0       2     1     2.6     2   1
## 3  37   1  3      130  250   0       0     0     3.5     3   0
## 4  41   0  2      130  204   0       2     0     1.4     1   0
\end{verbatim}

A continuación, analizamos la correlación entre las variables mediante
las distancias, mediante la métrica del máximum. Para su visualización
utilizamos un mapa de calor con 15 instancias. Sólo visualizamos las
primeras 2 filas

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Matriz de distancias}
\NormalTok{distancias }\OtherTok{\textless{}{-}} \FunctionTok{as.matrix}\NormalTok{(}\FunctionTok{dist}\NormalTok{(data\_num, }\AttributeTok{method =} \StringTok{\textquotesingle{}maximum\textquotesingle{}}\NormalTok{))}
\FunctionTok{head}\NormalTok{(distancias,}\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    1  2  3  4  5  6   7  8  9 10 11 12 13 14  15 16 17 18 19 20 21 22 23 24 25
## 1  0 57 36 82 50 20  68 32 83 94 20 30 40 87 118 57 47 30 30 75 10 40 62 80 67
## 2 57  0 30 26 11 39 125 25 26 37 65 27 34 52  61 19 20 46 37 18 54 55 12 23 17
##    26 27 28  29 30 31  32 33 34 35  36 37  38 39 40 41 42 43  44 45  46 47  48
## 1  54 60 39 119 47 56  49 52 53 60 109 10  67 43 61 87 16 74  44 56 111 43 131
## 2 111 30 30  62 20  7 106 15 23 25  52 47 124 30 30 30 73 30 101  9  54 30 188
##   49 50  51 52 53 54 55 56  57 58 59 60  61 62 63 64 65  66 67 68 69 70 71 72
## 1 89 88 109 48 67 33 36 53 114 35 73 30 109 70 25 98 15 101 54 40 55 17 35 40
## 2 32 31  52 61 23 24 37 20  57 44 16 76  52 13 75 41 53  44 30 97 30 40 25 38
##   73 74  75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90  91 92  93 94 95 96 97
## 1 50 89  74 35 22 41 16 78 30 35 20 40 51 29 70 52 30 40 122 55 145 34 32 50 28
## 2 19 32 131 29 79 19 41 22 35 92 60 96 23 28 14 18 27 73  65 10  88 23 26 10 30
##   98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
## 1 85 64  45 104  32  50  98  52 109  57  40  67  21  37 100  55  30  83  75 103
## 2 28 19  31  47  74  36  41  80  52  10  31  28  78  20  43 112  34  26  20  46
##   118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136
## 1  44  32  30 121  64  69  22  52  40  50  66  77  40  66  82  25  73  36 112
## 2 101  25  27 178  20  20  53  22  80  13  23  20  29  26  38  32  24  21  55
##   137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155
## 1  40  88  41  65  10  81  35  55  52  10  48  32  58  15  58 278  12  40  36
## 2  52  32  16  20  59  24  80  15  20  60  26  79  89  69  36 335  60  17  93
##   156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174
## 1  20  35  20  42  89  35  72  60  36  79  63  28  34 126  17  60  37 108  74
## 2  70  71  64  48  32  75  15  20  26  22  18  59  53  69  40  22  54 165  25
##   175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192 193
## 1  12  53 102  30  40  36 123  42  18  19  91  46  40  32  32  90  20  39  22
## 2  45  15  45  86  17  45 180  28  58  76  34  25  40  72  25  33  69  24  65
##   194 195 196 197 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212
## 1  75  60  52  50  42  13  50  39 160  27  75  23  32  86  30  42  71  55  72
## 2  18  70  40  22  17  44  25  96 103  84  24  80  30  29  33  30  30  29  26
##   213 214 215 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231
## 1  58  56  93  82  43  30  22  48  52  87  37  52  76  82   9  80  74  90  41
## 2  58  15  36  25  21  74  42  39  38  30  53  40  33  25  48  23  17  33  98
##   232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250
## 1 137  40  85  38  30  40  26  40  51  34  30  52 108  49  60  50  74  78  85
## 2  80  40  40  57  54  21  42  66  26  77  40  14  51   8  20  46  17  21  28
##   251 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269
## 1  68  32  40  45  77  63  89  41  36  44  33  46  60 120  29  82  68  63 106
## 2  26  34  66  74  25  14  32  36  32  23  90  30  23  63  86  25  11  32  49
##   270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287 288
## 1  79  58  25 137  82  59  14  66  54  89  50  33  81  94  83  46  61  66  65
## 2  22  40  82  80  25  50  49  28  34  32 106  24  24  37  28  89  50   9  11
##   289 290 291 292 293 294 295 296 297 298 299 300 301 302
## 1  46  74  56 117  99  89 129 110  45  50  93 155  50 111
## 2  11  32 113  60  42  32  72  53  20  35  36  98  10  54
\end{verbatim}

Pero no se interpretan muy bien estos valores, para ello, realizamos un
mapa de calor para 15 instancias con la métrica de pearson.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Correlación basada en el método de la distancia}
\NormalTok{res.dist }\OtherTok{\textless{}{-}} \FunctionTok{get\_dist}\NormalTok{(data\_num[}\DecValTok{1}\SpecialCharTok{:}\DecValTok{15}\NormalTok{,], }\AttributeTok{method =} \StringTok{"pearson"}\NormalTok{)}

\CommentTok{\# Visualize the dissimilarity matrix}
\FunctionTok{fviz\_dist}\NormalTok{(res.dist, }\AttributeTok{lab\_size =} \DecValTok{5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{methods-II_files/figure-latex/unnamed-chunk-12-1.pdf}

En este gráfico se representan de color azul las distancias más grandes,
siendo el valor máximo 0.12 y el mínimo 0.0 con el color rosa, no
obstante podemos observar que son más los valores cuyas distancias son
mínimas respecto a los valores con mayor distancias.

Teniendo en cuenta que en el conjunto de datos encontramos valores desde
0 a 259, para tener una estandarización de los mismos, consideramos
escalar el conjunto de datos, donde cada atributo tiene media 0 y
desviación típica de 1. No escalamos la variable objetivo num. Por otro
lado, vamos a cambiar el nombre de la variable objetivo de num a
`diagnosis'.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Escalamos el conjunto de datos sin las variables: ca, thal, thalach, num.}
\CommentTok{\#tem \textless{}{-} data\_num[,{-}12]}
\CommentTok{\#tem \textless{}{-} data\_num[,{-}8]}
\NormalTok{data\_scale }\OtherTok{\textless{}{-}} \FunctionTok{scale}\NormalTok{(data\_num[,}\SpecialCharTok{{-}}\DecValTok{11}\NormalTok{]) }\CommentTok{\# 11 es el índice de la variable objetivo num}
\FunctionTok{head}\NormalTok{(data\_scale,}\DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##            age       sex         cp    trestbps        chol        fbs
## [1,]  1.392608 0.6867343  0.8750283  1.60992387  0.75711513 -0.4122838
## [2,]  1.392608 0.6867343  0.8750283 -0.66122880 -0.34206509 -0.4122838
## [3,] -1.925916 0.6867343 -0.1736167 -0.09344064  0.06289604 -0.4122838
##         restecg      exang   oldpeak     slope
## [1,]  1.0184230  1.4295857 0.4002414 0.6601533
## [2,]  1.0184230  1.4295857 1.3479263 0.6601533
## [3,] -0.9917976 -0.6971871 2.1233048 2.2943034
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Vector con datos escalados}
\NormalTok{vector1 }\OtherTok{\textless{}{-}}\NormalTok{ data\_scale}

\CommentTok{\#Vector de la variable objetivo}
\NormalTok{vector2 }\OtherTok{\textless{}{-}}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{num}

\CommentTok{\# Combinamos los dos vectores usando cbind()}
\NormalTok{data1 }\OtherTok{\textless{}{-}} \FunctionTok{cbind}\NormalTok{(vector1,vector2)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{head}\NormalTok{(data1, }\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##           age       sex        cp   trestbps       chol        fbs  restecg
## [1,] 1.392608 0.6867343 0.8750283  1.6099239  0.7571151 -0.4122838 1.018423
## [2,] 1.392608 0.6867343 0.8750283 -0.6612288 -0.3420651 -0.4122838 1.018423
##         exang   oldpeak     slope vector2
## [1,] 1.429586 0.4002414 0.6601533       2
## [2,] 1.429586 1.3479263 0.6601533       1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Aplicamos los nombres a las columnas}
\FunctionTok{colnames}\NormalTok{(data1) }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{\textquotesingle{}age\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}sex\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}cp\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}trestbps\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}chol\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}fbs\textquotesingle{}}\NormalTok{,}
                    \StringTok{\textquotesingle{}restecg\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}exang\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}oldpeak\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}slope\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}diagnosis\textquotesingle{}}\NormalTok{)}

\CommentTok{\#Lo convertimos en un dataframe}
\NormalTok{data1 }\OtherTok{\textless{}{-}} \FunctionTok{as.data.frame}\NormalTok{(data1)}
\FunctionTok{head}\NormalTok{(data1, }\DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         age       sex         cp    trestbps        chol        fbs    restecg
## 1  1.392608 0.6867343  0.8750283  1.60992387  0.75711513 -0.4122838  1.0184230
## 2  1.392608 0.6867343  0.8750283 -0.66122880 -0.34206509 -0.4122838  1.0184230
## 3 -1.925916 0.6867343 -0.1736167 -0.09344064  0.06289604 -0.4122838 -0.9917976
##        exang   oldpeak     slope diagnosis
## 1  1.4295857 0.4002414 0.6601533         2
## 2  1.4295857 1.3479263 0.6601533         1
## 3 -0.6971871 2.1233048 2.2943034         0
\end{verbatim}

Si analizamos los valores del atributo `diagnosis', podemos ver que toma
un valor de 2, pero de acuerdo a la información del conjunto de datos,
esta variable sólo puede tomar valores de 0 y 1. Veamos qué valores
numéricos tiene este atributo

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{freq }\OtherTok{\textless{}{-}} \FunctionTok{as.data.frame}\NormalTok{(}\FunctionTok{table}\NormalTok{(data1}\SpecialCharTok{$}\NormalTok{diagnosis))}
\NormalTok{freq}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Var1 Freq
## 1    0  163
## 2    1   55
## 3    2   36
## 4    3   35
## 5    4   13
\end{verbatim}

Basado en la tabla anterior, la variable `diagnosis' toma valores de
0,1,2,3 y 4. En consecuencia, vamos a remover los datos con valores de
2,3 y 4. Ahora bien, una vez terminado esto, vamos a clasificar los
datos de 0 como `healthy' y de 1 como `heartDisease'.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data1 }\OtherTok{\textless{}{-}}\NormalTok{ data1[(data1}\SpecialCharTok{$}\NormalTok{diagnosis}\SpecialCharTok{==}\StringTok{"0"} \SpecialCharTok{|}\NormalTok{ data1}\SpecialCharTok{$}\NormalTok{diagnosis}\SpecialCharTok{==}\StringTok{"1"}\NormalTok{),]}
\FunctionTok{head}\NormalTok{(data1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##          age        sex         cp    trestbps        chol        fbs
## 2  1.3926081  0.6867343  0.8750283 -0.66122880 -0.34206509 -0.4122838
## 3 -1.9259163  0.6867343 -0.1736167 -0.09344064  0.06289604 -0.4122838
## 4 -1.4834463 -1.4513456 -1.2222618 -0.09344064 -0.82416167 -0.4122838
## 5  0.1758159  0.6867343 -1.2222618 -0.66122880 -0.20707804 -0.4122838
## 7  0.2864333 -1.4513456  0.8750283 -0.66122880  2.06841784 -0.4122838
## 9 -0.1560366  0.6867343  0.8750283  0.47434753 -0.84344553  2.4174822
##      restecg      exang    oldpeak      slope diagnosis
## 2  1.0184230  1.4295857  1.3479263  0.6601533         1
## 3 -0.9917976 -0.6971871  2.1233048  2.2943034         0
## 4  1.0184230 -0.6971871  0.3140882 -0.9739967         0
## 5 -0.9917976 -0.6971871 -0.2028308 -0.9739967         0
## 7 -0.9917976  1.4295857 -0.3751372 -0.9739967         0
## 9  1.0184230  1.4295857  1.7786922  2.2943034         1
\end{verbatim}

Podemos ver que la variable diagnosis toma valores de 0 y 1 como
esperábamos. Ahora la dimensión del conjunto de datos es 218 instancias
y 11 columnas.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{dim}\NormalTok{(data1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 218  11
\end{verbatim}

Por lo que hemos reducido el número de instancias de 302 a 218. Para una
mejor comprensión de los datos, vamos a

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Reasignamos los diagnósticos como healty y heartDisease}
\NormalTok{data1}\SpecialCharTok{$}\NormalTok{diagnosis[data1}\SpecialCharTok{$}\NormalTok{diagnosis }\SpecialCharTok{==} \DecValTok{0}\NormalTok{] }\OtherTok{\textless{}{-}} \StringTok{"healthy"}
\NormalTok{data1}\SpecialCharTok{$}\NormalTok{diagnosis[data1}\SpecialCharTok{$}\NormalTok{diagnosis }\SpecialCharTok{==} \DecValTok{1}\NormalTok{] }\OtherTok{\textless{}{-}} \StringTok{"heartDisease"}

\CommentTok{\#Visualizamos los datos de las 3 primeras columnas}
\FunctionTok{head}\NormalTok{(data1,}\DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         age        sex         cp    trestbps        chol        fbs    restecg
## 2  1.392608  0.6867343  0.8750283 -0.66122880 -0.34206509 -0.4122838  1.0184230
## 3 -1.925916  0.6867343 -0.1736167 -0.09344064  0.06289604 -0.4122838 -0.9917976
## 4 -1.483446 -1.4513456 -1.2222618 -0.09344064 -0.82416167 -0.4122838  1.0184230
##        exang   oldpeak      slope    diagnosis
## 2  1.4295857 1.3479263  0.6601533 heartDisease
## 3 -0.6971871 2.1233048  2.2943034      healthy
## 4 -0.6971871 0.3140882 -0.9739967      healthy
\end{verbatim}

A partir de ahora nuestros datos están estandarizados.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data2 }\OtherTok{\textless{}{-}} \FunctionTok{as.data.frame}\NormalTok{(data1)}

\CommentTok{\#Activamos las variables del dataset para llamarlas sin recurrir al conjunto de datos "data2"}
\FunctionTok{attach}\NormalTok{(data2)}
\FunctionTok{head}\NormalTok{(data2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##          age        sex         cp    trestbps        chol        fbs
## 2  1.3926081  0.6867343  0.8750283 -0.66122880 -0.34206509 -0.4122838
## 3 -1.9259163  0.6867343 -0.1736167 -0.09344064  0.06289604 -0.4122838
## 4 -1.4834463 -1.4513456 -1.2222618 -0.09344064 -0.82416167 -0.4122838
## 5  0.1758159  0.6867343 -1.2222618 -0.66122880 -0.20707804 -0.4122838
## 7  0.2864333 -1.4513456  0.8750283 -0.66122880  2.06841784 -0.4122838
## 9 -0.1560366  0.6867343  0.8750283  0.47434753 -0.84344553  2.4174822
##      restecg      exang    oldpeak      slope    diagnosis
## 2  1.0184230  1.4295857  1.3479263  0.6601533 heartDisease
## 3 -0.9917976 -0.6971871  2.1233048  2.2943034      healthy
## 4  1.0184230 -0.6971871  0.3140882 -0.9739967      healthy
## 5 -0.9917976 -0.6971871 -0.2028308 -0.9739967      healthy
## 7 -0.9917976  1.4295857 -0.3751372 -0.9739967      healthy
## 9  1.0184230  1.4295857  1.7786922  2.2943034 heartDisease
\end{verbatim}

También podemos visualizar mediante un gráfico de pares (pair-plot), las
relaciones de los datos escalados de acuerdo a su diagnóstico

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Pair{-}plot de las características}
\FunctionTok{ggpairs}\NormalTok{(data2[,}\DecValTok{1}\SpecialCharTok{:}\DecValTok{5}\NormalTok{], }\FunctionTok{aes}\NormalTok{(}\AttributeTok{colour=}\FunctionTok{factor}\NormalTok{(data2}\SpecialCharTok{$}\NormalTok{diagnosis), }\AttributeTok{alpha=}\FloatTok{0.2}\NormalTok{)) }
\end{Highlighting}
\end{Shaded}

\includegraphics{methods-II_files/figure-latex/unnamed-chunk-22-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Pair{-}plot de las características}
\FunctionTok{ggpairs}\NormalTok{(data2[,}\DecValTok{6}\SpecialCharTok{:}\DecValTok{10}\NormalTok{], }\FunctionTok{aes}\NormalTok{(}\AttributeTok{colour=}\FunctionTok{factor}\NormalTok{(data2}\SpecialCharTok{$}\NormalTok{diagnosis), }\AttributeTok{alpha=}\FloatTok{0.2}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{methods-II_files/figure-latex/unnamed-chunk-23-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(data2, }
       \FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ age, }
           \AttributeTok{y=}\NormalTok{chol)) }\SpecialCharTok{+}
\FunctionTok{geom\_point}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{methods-II_files/figure-latex/unnamed-chunk-24-1.pdf}

Antes de continuar con el análisis, con los datos estandarizados, vale
la pena observar la relación entre la edad y los niveles de azúcar en la
sangre. Lo anterior se ve mejor sin la normalización.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(data\_num, }
       \FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ age, }
           \AttributeTok{y=}\NormalTok{chol)) }\SpecialCharTok{+}
\FunctionTok{geom\_point}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{methods-II_files/figure-latex/unnamed-chunk-25-1.pdf}

Por otro lado, en general las personas con problemas del corazón tienen
una edad más avanzada.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p0 }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(data2, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ age, }\AttributeTok{fill =}\NormalTok{ diagnosis)) }\SpecialCharTok{+}
\FunctionTok{geom\_histogram}\NormalTok{(}\AttributeTok{binwidth =}\NormalTok{ .}\DecValTok{5}\NormalTok{)}
\NormalTok{p1 }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(data2, }\FunctionTok{aes}\NormalTok{(diagnosis, age)) }\SpecialCharTok{+} \FunctionTok{geom\_boxplot}\NormalTok{()}
\NormalTok{p0 }\SpecialCharTok{+}\NormalTok{ p1}
\end{Highlighting}
\end{Shaded}

\includegraphics{methods-II_files/figure-latex/unnamed-chunk-26-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p2 }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(data2, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ cp, }\AttributeTok{fill =}\NormalTok{ diagnosis)) }\SpecialCharTok{+}
\FunctionTok{geom\_histogram}\NormalTok{(}\AttributeTok{binwidth =}\NormalTok{ .}\DecValTok{5}\NormalTok{)}
\NormalTok{p3 }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(data2, }\FunctionTok{aes}\NormalTok{(diagnosis, cp)) }\SpecialCharTok{+} \FunctionTok{geom\_boxplot}\NormalTok{()}
\NormalTok{p2 }\SpecialCharTok{+}\NormalTok{ p3}
\end{Highlighting}
\end{Shaded}

\includegraphics{methods-II_files/figure-latex/unnamed-chunk-27-1.pdf}

\hypertarget{modelado-usando-submuestras}{%
\subsection{Modelado usando
submuestras}\label{modelado-usando-submuestras}}

Definimos la submuestra del conjunto de datos. Examinaremos la capacidad
predictiva de un modelo, para ello, vamos a utilizar un 70\% de los
objetos para entrenar y un 30\% para evaluar dicho modelo.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n }\OtherTok{\textless{}{-}} \FunctionTok{dim}\NormalTok{(data2)[}\DecValTok{1}\NormalTok{]}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{12}\NormalTok{)}
\NormalTok{indices\_aprendizaje }\OtherTok{\textless{}{-}} \FunctionTok{sample}\NormalTok{(n, }\FunctionTok{round}\NormalTok{(.}\DecValTok{7}\SpecialCharTok{*}\NormalTok{n))}
\NormalTok{data\_aprendizaje }\OtherTok{\textless{}{-}}\NormalTok{ data2[indices\_aprendizaje, ]}
\FunctionTok{head}\NormalTok{(data\_aprendizaje)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##            age        sex         cp    trestbps       chol        fbs
## 263 -1.1515939  0.6867343 -0.1736167 -0.66122880 -0.3999167 -0.4122838
## 125 -1.0409764 -1.4513456 -1.2222618 -0.09344064 -0.2456458 -0.4122838
## 105 -0.0454191  0.6867343 -1.2222618 -1.34257460  1.2006440 -0.4122838
## 128 -1.1515939  0.6867343 -1.2222618 -0.66122880 -0.5156199 -0.4122838
## 238 -0.5985065 -1.4513456 -1.2222618  0.13367463  0.4678572 -0.4122838
## 270  0.7289033  0.6867343  0.8750283  0.47434753 -0.7663101 -0.4122838
##        restecg      exang    oldpeak      slope    diagnosis
## 263 -0.9917976 -0.6971871 -0.8920562 -0.9739967      healthy
## 125  1.0184230 -0.6971871 -0.3751372  0.6601533      healthy
## 105 -0.9917976 -0.6971871 -0.8920562 -0.9739967      healthy
## 128 -0.9917976 -0.6971871 -0.8920562 -0.9739967      healthy
## 238 -0.9917976 -0.6971871 -0.8920562  0.6601533      healthy
## 270  1.0184230  1.4295857  0.7448541 -0.9739967 heartDisease
\end{verbatim}

Veamos el conjunto de test:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data\_test }\OtherTok{\textless{}{-}}\NormalTok{ data2[}\SpecialCharTok{{-}}\NormalTok{indices\_aprendizaje, ]}
\FunctionTok{head}\NormalTok{(data\_test)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##           age        sex         cp    trestbps       chol        fbs
## 9  -0.1560366  0.6867343  0.8750283  0.47434753 -0.8434455  2.4174822
## 13 -1.1515939  0.6867343 -1.2222618 -0.66122880  0.3135863 -0.4122838
## 27  1.2819907 -1.4513456 -2.2709068  1.04213570 -0.3999167 -0.4122838
## 32  1.0607557  0.6867343 -0.1736167  0.47434753  1.7020244 -0.4122838
## 33  0.5076683  0.6867343  0.8750283  0.19045345 -0.2456458 -0.4122838
## 34 -1.1515939  0.6867343 -0.1736167 -0.09344064 -0.2649296 -0.4122838
##       restecg      exang    oldpeak      slope    diagnosis
## 9   1.0184230  1.4295857  1.7786922  2.2943034 heartDisease
## 13 -0.9917976 -0.6971871 -0.8920562 -0.9739967      healthy
## 27 -0.9917976 -0.6971871  1.3479263  2.2943034      healthy
## 32 -0.9917976 -0.6971871 -0.8920562 -0.9739967 heartDisease
## 33 -0.9917976 -0.6971871 -0.4612903  0.6601533      healthy
## 34 -0.9917976  1.4295857 -0.5474435 -0.9739967      healthy
\end{verbatim}

Ya tenemos las submuestras, a partir de aquí vamos a entrenar un modelo
y posteriormente testar. Para empezar vamos a utilizar un modelo de
regresión lineal múltiple que explique la salud del corazón en función
del resto de la variables.

Ajustamos el modelo usando los datos de entrenamiento.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{na.omit}\NormalTok{(data\_aprendizaje)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##             age        sex         cp    trestbps         chol        fbs
## 263 -1.15159390  0.6867343 -0.1736167 -0.66122880 -0.399916677 -0.4122838
## 125 -1.04097642 -1.4513456 -1.2222618 -0.09344064 -0.245645770 -0.4122838
## 105 -0.04541910  0.6867343 -1.2222618 -1.34257460  1.200643985 -0.4122838
## 128 -1.15159390  0.6867343 -1.2222618 -0.66122880 -0.515619857 -0.4122838
## 238 -0.59850650 -1.4513456 -1.2222618  0.13367463  0.467857176 -0.4122838
## 270  0.72890326  0.6867343  0.8750283  0.47434753 -0.766310081 -0.4122838
## 90   1.28199067  0.6867343  0.8750283 -0.66122880  1.065656941 -0.4122838
## 46  -0.37727154  0.6867343 -0.1736167 -1.22901697 -1.383393710 -0.4122838
## 184  0.61828578 -1.4513456  0.8750283  1.49636623  1.123508531 -0.4122838
## 297  0.28643334 -1.4513456  0.8750283  0.47434753 -0.110658726 -0.4122838
## 110  0.72890326 -1.4513456  0.8750283  0.75824162  1.162076258 -0.4122838
## 169 -1.04097642 -1.4513456 -1.2222618 -1.11545934 -1.672651661 -0.4122838
## 165  0.28643334  0.6867343  0.8750283  0.02011700 -0.766310081 -0.4122838
## 51   1.17137319  0.6867343  0.8750283 -0.66122880 -1.344825983 -0.4122838
## 148 -1.04097642  0.6867343 -1.2222618 -0.20699827  1.181360121 -0.4122838
## 145 -0.81974146  0.6867343 -0.1736167 -1.34257460 -0.072090999 -0.4122838
## 240 -1.48344634  0.6867343 -1.2222618 -1.22901697 -0.226361906 -0.4122838
## 17  -0.04541910  0.6867343  0.8750283  0.47434753 -0.149226453 -0.4122838
## 252  1.06075570  0.6867343  0.8750283 -0.20699827  0.313586269 -0.4122838
## 269 -1.37282886  0.6867343 -0.1736167 -0.09344064 -1.286974393 -0.4122838
## 208  0.06519838  0.6867343 -1.2222618 -0.09344064  0.294302405 -0.4122838
## 76   0.61828578  0.6867343  0.8750283 -0.37733472  0.217166952 -0.4122838
## 94   0.95013822 -1.4513456 -0.1736167  0.19045345  0.101463771 -0.4122838
## 172  0.50766830 -1.4513456  0.8750283  2.40482730  0.043612181 -0.4122838
## 166 -0.26665406  0.6867343 -0.1736167  0.36078990 -0.457768267 -0.4122838
## 233  2.16693051 -1.4513456 -1.2222618 -0.66122880  0.429289449 -0.4122838
## 295 -1.48344634  0.6867343 -1.2222618 -0.66122880 -1.730503251 -0.4122838
## 142 -0.26665406  0.6867343 -1.2222618 -0.20699827 -0.804877808  2.4174822
## 41  -1.59406382  0.6867343 -2.2709068  0.47434753 -0.920580989 -0.4122838
## 224  0.95013822 -1.4513456  0.8750283 -1.34257460  0.429289449 -0.4122838
## 281 -0.81974146  0.6867343 -0.1736167 -0.09344064  0.120747635 -0.4122838
## 290  1.39260815  0.6867343 -0.1736167  1.15569333 -0.669890764 -0.4122838
## 226 -0.81974146  0.6867343  0.8750283 -1.11545934 -0.824161672 -0.4122838
## 93  -1.15159390 -1.4513456 -0.1736167 -1.34257460 -2.039045065 -0.4122838
## 210 -1.92591626 -1.4513456 -0.1736167 -0.66122880 -0.612039174 -0.4122838
## 43   0.50766830  0.6867343 -0.1736167  1.04213570 -0.669890764  2.4174822
## 112 -0.26665406  0.6867343 -2.2709068 -0.77478644 -1.171271213 -0.4122838
## 201  1.06075570 -1.4513456  0.8750283  2.74550020  1.509185799 -0.4122838
## 25  -0.48788902 -1.4513456 -0.1736167 -0.66122880 -0.534903721 -0.4122838
## 250  0.28643334  0.6867343  0.8750283 -1.22901697 -0.882013262 -0.4122838
## 5    0.17581586  0.6867343 -1.2222618 -0.66122880 -0.207078043 -0.4122838
## 192 -1.26221138  0.6867343  0.8750283  0.02011700  0.005044454  2.4174822
## 152  1.39260815 -1.4513456 -0.1736167 -0.94512289  6.118029150 -0.4122838
## 288  0.17581586  0.6867343 -1.2222618 -0.09344064 -0.496335994 -0.4122838
## 257  2.38816547 -1.4513456 -0.1736167  0.47434753 -0.959148715 -0.4122838
## 63  -0.04541910 -1.4513456 -0.1736167  0.19045345  1.104224668  2.4174822
## 253 -0.37727154 -1.4513456 -0.1736167 -0.66122880  0.930669897 -0.4122838
## 35  -1.37282886  0.6867343  0.8750283  0.47434753 -0.399916677 -0.4122838
## 101 -2.25776870  0.6867343 -2.2709068 -0.77478644 -1.248406666 -0.4122838
## 244  0.61828578 -1.4513456 -0.1736167 -0.66122880 -1.325542120  2.4174822
## 143  1.06075570  0.6867343 -0.1736167 -0.37733472  1.200643985 -0.4122838
## 179 -0.15603658  0.6867343 -0.1736167 -0.09344064 -0.014239409  2.4174822
## 199  0.50766830  0.6867343 -2.2709068  1.60992387  0.506424903 -0.4122838
## 115 -1.48344634  0.6867343 -1.2222618  0.19045345 -0.843445535 -0.4122838
## 77  -0.37727154 -1.4513456 -0.1736167  0.47434753  1.181360121 -0.4122838
## 275  1.06075570  0.6867343 -2.2709068  2.17771203 -0.380632814 -0.4122838
## 218  1.06075570 -1.4513456  0.8750283 -0.09344064  1.084940804 -0.4122838
## 122 -0.37727154  0.6867343 -0.1736167 -1.79680514 -0.477052131 -0.4122838
## 53  -1.15159390  0.6867343 -1.2222618 -0.09344064 -0.534903721 -0.4122838
## 37   0.28643334  0.6867343  0.8750283  1.04213570  0.564276493 -0.4122838
## 54   0.61828578  0.6867343  0.8750283 -0.09344064  0.120747635 -0.4122838
## 19  -0.59850650  0.6867343 -1.2222618 -0.09344064  0.371437859 -0.4122838
## 227  1.39260815 -1.4513456 -0.1736167  1.15569333  0.583560356 -0.4122838
## 183  0.50766830  0.6867343 -2.2709068  2.63194257  0.448573312 -0.4122838
## 18  -0.70912398 -1.4513456 -0.1736167 -0.09344064  0.544992629 -0.4122838
## 98  -0.26665406  0.6867343 -1.2222618  0.13367463 -0.882013262 -0.4122838
## 190 -0.48788902  0.6867343 -0.1736167 -0.15021945 -0.978432579 -0.4122838
## 56  -0.48788902  0.6867343 -0.1736167  0.47434753 -0.264929633 -0.4122838
## 298 -1.04097642  0.6867343 -2.2709068 -1.22901697  0.332870132 -0.4122838
## 254 -1.26221138  0.6867343  0.8750283 -0.94512289  1.084940804 -0.4122838
## 99  -0.70912398  0.6867343  0.8750283 -0.54767117 -0.477052131 -0.4122838
## 28  -1.26221138  0.6867343  0.8750283  1.04213570  0.005044454 -0.4122838
## 88  -0.15603658 -1.4513456  0.8750283  0.36078990 -0.245645770 -0.4122838
## 159  1.50322563  0.6867343 -0.1736167 -0.77478644  0.583560356 -0.4122838
## 271  1.28199067  0.6867343  0.8750283  1.60992387 -0.361348950 -0.4122838
## 202  0.28643334  0.6867343 -0.1736167  1.04213570 -2.328303016  2.4174822
## 225 -2.25776870 -1.4513456 -1.2222618 -0.77478644 -0.708458491 -0.4122838
## 196  1.61384311  0.6867343 -2.2709068  1.60992387 -0.245645770  2.4174822
## 116  0.39705082  0.6867343 -0.1736167  0.47434753 -0.689174628  2.4174822
## 204 -1.26221138  0.6867343  0.8750283 -1.22901697 -0.689174628 -0.4122838
## 20   1.06075570  0.6867343 -2.2709068 -1.22901697 -0.689174628 -0.4122838
## 214 -0.26665406  0.6867343  0.8750283 -1.11545934 -0.322781223 -0.4122838
## 111  0.17581586  0.6867343  0.8750283 -0.37733472  0.043612181  2.4174822
## 14  -0.26665406  0.6867343 -0.1736167  2.29126967 -0.920580989  2.4174822
## 67  -0.04541910  0.6867343 -0.1736167  1.04213570 -0.284213497 -0.4122838
## 2    1.39260815  0.6867343  0.8750283 -0.66122880 -0.342065087 -0.4122838
## 234 -0.04541910 -1.4513456 -0.1736167  1.60992387 -0.882013262 -0.4122838
## 58  -0.04541910  0.6867343 -0.1736167 -0.37733472  0.506424903 -0.4122838
## 163  0.39705082 -1.4513456  0.8750283 -1.79680514  0.024328318 -0.4122838
## 16  -0.70912398  0.6867343 -1.2222618 -1.22901697 -0.342065087 -0.4122838
## 74  -1.15159390  0.6867343  0.8750283 -1.22901697 -0.959148715 -0.4122838
## 22   0.39705082  0.6867343 -1.2222618 -0.66122880  0.718547400 -0.4122838
## 171 -0.15603658  0.6867343  0.8750283  0.58790517 -0.399916677 -0.4122838
## 294  0.95013822 -1.4513456  0.8750283 -0.43411354 -0.959148715 -0.4122838
## 81  -0.15603658 -1.4513456  0.8750283 -0.09344064  0.332870132 -0.4122838
## 173  0.83952074 -1.4513456  0.8750283  0.47434753  2.839772373 -0.4122838
## 268 -1.59406382  0.6867343  0.8750283  1.15569333 -0.457768267 -0.4122838
## 232 -0.59850650  0.6867343 -0.1736167 -0.77478644 -1.884774158 -0.4122838
## 219  0.50766830  0.6867343  0.8750283  0.36078990  0.467857176 -0.4122838
## 160 -0.93035894  0.6867343 -1.2222618 -1.74002632 -0.959148715  2.4174822
## 11   0.17581586 -1.4513456 -1.2222618  0.47434753  0.911386034 -0.4122838
## 95  -0.26665406  0.6867343  0.8750283 -0.20699827  0.159315361 -0.4122838
## 221 -0.04541910 -1.4513456 -0.1736167 -1.34257460  0.390721722 -0.4122838
## 239 -1.37282886  0.6867343 -1.2222618 -0.66122880  0.930669897 -0.4122838
## 209  0.83952074 -1.4513456  0.8750283  1.04213570 -0.052807136 -0.4122838
## 26   0.39705082 -1.4513456 -0.1736167 -0.66122880  1.798443750 -0.4122838
## 132 -2.81085610  0.6867343 -1.2222618 -0.09344064 -0.824161672 -0.4122838
## 78  -0.70912398  0.6867343 -1.2222618 -0.09344064 -0.033523272 -0.4122838
## 262  0.61828578 -1.4513456 -2.2709068  1.04213570 -0.129942589 -0.4122838
## 7    0.28643334 -1.4513456  0.8750283 -0.66122880  2.068417837 -0.4122838
## 10   0.28643334  0.6867343  0.8750283  0.47434753 -1.055568032 -0.4122838
## 4   -1.48344634 -1.4513456 -1.2222618 -0.09344064 -0.824161672 -0.4122838
## 255 -1.37282886 -1.4513456 -0.1736167 -0.66122880 -0.727742355 -0.4122838
## 291  0.06519838 -1.4513456 -1.2222618  0.02011700  1.837011477 -0.4122838
## 168 -2.14715122  0.6867343  0.8750283 -0.32055590  0.679979673 -0.4122838
## 39   0.72890326  0.6867343 -0.1736167  1.04213570 -0.072090999  2.4174822
## 185  0.95013822 -1.4513456 -1.2222618  0.47434753 -0.997716442 -0.4122838
## 237 -0.93035894  0.6867343  0.8750283 -0.66122880  0.043612181 -0.4122838
## 175  0.28643334  0.6867343  0.8750283  1.15569333  0.525708766 -0.4122838
## 3   -1.92591626  0.6867343 -0.1736167 -0.09344064  0.062896045 -0.4122838
## 162 -0.04541910 -1.4513456 -0.1736167 -1.22901697 -0.631323038 -0.4122838
## 80  -1.04097642  0.6867343  0.8750283 -1.56968987 -0.747026218 -0.4122838
## 86  -0.81974146  0.6867343 -0.1736167  0.36078990  0.197883088 -0.4122838
## 15   0.28643334  0.6867343 -0.1736167  1.04213570 -1.518380754 -0.4122838
## 247 -0.81974146  0.6867343  0.8750283 -1.22901697  0.544992629 -0.4122838
## 215  0.17581586  0.6867343 -2.2709068 -0.66122880 -1.036284169 -0.4122838
## 131 -0.37727154  0.6867343 -0.1736167 -2.13747804 -0.380632814 -0.4122838
## 21   0.39705082 -1.4513456 -2.2709068  1.04213570  0.699263536  2.4174822
## 167 -0.04541910 -1.4513456 -1.2222618  0.02011700  0.795682853  2.4174822
## 44   0.72890326 -1.4513456  0.8750283 -0.09344064  1.605605116 -0.4122838
## 57  -1.48344634  0.6867343  0.8750283 -1.22901697 -1.441245300 -0.4122838
## 69  -0.93035894  0.6867343 -0.1736167  1.04213570 -0.303497360 -0.4122838
## 249  0.83952074  0.6867343 -1.2222618 -0.20699827 -0.747026218  2.4174822
## 301  0.28643334 -1.4513456 -1.2222618 -0.09344064 -0.207078043 -0.4122838
## 216 -0.93035894 -1.4513456 -1.2222618 -1.51291105 -0.824161672 -0.4122838
## 188 -0.04541910  0.6867343 -1.2222618  3.42684600  0.699263536 -0.4122838
## 259  0.28643334  0.6867343 -1.2222618 -0.43411354  0.275018542 -0.4122838
## 62   0.39705082  0.6867343  0.8750283 -0.20699827 -0.592755311 -0.4122838
## 164 -0.70912398  0.6867343 -0.1736167 -0.43411354  0.159315361  2.4174822
## 30   1.61384311 -1.4513456 -2.2709068  0.47434753 -0.149226453 -0.4122838
## 124  1.17137319  0.6867343 -2.2709068  0.36078990  0.679979673  2.4174822
## 133 -0.37727154  0.6867343  0.8750283  0.47434753  0.275018542 -0.4122838
## 194  1.50322563 -1.4513456 -0.1736167 -0.66122880 -0.689174628 -0.4122838
## 102  0.28643334 -1.4513456  0.8750283 -0.20699827  1.084940804 -0.4122838
## 151 -1.37282886 -1.4513456  0.8750283 -1.68324750  0.352153995 -0.4122838
## 230 -0.26665406 -1.4513456 -0.1736167  0.24723226 -0.978432579 -0.4122838
## 84  -0.26665406  0.6867343 -1.2222618 -0.66122880  1.509185799 -0.4122838
## 242 -0.59850650 -1.4513456  0.8750283 -0.09344064  0.429289449 -0.4122838
## 147 -1.48344634  0.6867343 -0.1736167 -1.11545934  0.062896045 -0.4122838
## 217 -0.93035894 -1.4513456  0.8750283  0.36078990 -0.072090999 -0.4122838
## 92   0.83952074  0.6867343 -0.1736167 -0.09344064 -0.303497360 -0.4122838
## 55  -0.04541910  0.6867343  0.8750283 -0.43411354  0.371437859 -0.4122838
## 273  1.83507807 -1.4513456  0.8750283 -1.11545934 -1.884774158 -0.4122838
##         restecg      exang     oldpeak      slope    diagnosis
## 263 -0.99179758 -0.6971871 -0.89205619 -0.9739967      healthy
## 125  1.01842302 -0.6971871 -0.37513716  0.6601533      healthy
## 105 -0.99179758 -0.6971871 -0.89205619 -0.9739967      healthy
## 128 -0.99179758 -0.6971871 -0.89205619 -0.9739967      healthy
## 238 -0.99179758 -0.6971871 -0.89205619  0.6601533      healthy
## 270  1.01842302  1.4295857  0.74485409 -0.9739967 heartDisease
## 90   1.01842302 -0.6971871 -0.54744350  0.6601533      healthy
## 46  -0.99179758 -0.6971871 -0.37513716 -0.9739967      healthy
## 184  1.01842302 -0.6971871 -0.89205619 -0.9739967 heartDisease
## 297 -0.99179758  1.4295857 -0.71974985  0.6601533 heartDisease
## 110  1.01842302  1.4295857 -0.03052447  0.6601533 heartDisease
## 169 -0.99179758 -0.6971871 -0.89205619  0.6601533      healthy
## 165 -0.99179758  1.4295857 -0.89205619 -0.9739967      healthy
## 51  -0.99179758 -0.6971871 -0.54744350 -0.9739967      healthy
## 148  1.01842302 -0.6971871 -0.89205619 -0.9739967      healthy
## 145 -0.99179758 -0.6971871 -0.89205619 -0.9739967 heartDisease
## 240 -0.99179758 -0.6971871 -0.89205619 -0.9739967      healthy
## 17  -0.99179758 -0.6971871  0.14178188 -0.9739967      healthy
## 252 -0.99179758  1.4295857 -0.71974985  0.6601533      healthy
## 269 -0.99179758 -0.6971871 -0.89205619 -0.9739967      healthy
## 208 -0.99179758 -0.6971871 -0.89205619 -0.9739967      healthy
## 76   1.01842302  1.4295857  1.52023264  0.6601533 heartDisease
## 94   1.01842302 -0.6971871 -0.89205619 -0.9739967      healthy
## 172 -0.99179758  1.4295857 -0.89205619  0.6601533 heartDisease
## 166 -0.99179758 -0.6971871 -0.89205619 -0.9739967      healthy
## 233  1.01842302  1.4295857 -0.71974985 -0.9739967      healthy
## 295 -0.99179758 -0.6971871 -0.89205619 -0.9739967      healthy
## 142 -0.99179758 -0.6971871 -0.89205619 -0.9739967      healthy
## 41  -0.99179758  1.4295857  0.31408822 -0.9739967      healthy
## 224 -0.99179758  1.4295857  0.65870091  0.6601533 heartDisease
## 281 -0.99179758 -0.6971871 -0.89205619 -0.9739967      healthy
## 290  1.01842302 -0.6971871 -0.20283081  0.6601533 heartDisease
## 226 -0.99179758 -0.6971871 -0.80590302 -0.9739967      healthy
## 93  -0.99179758 -0.6971871 -0.37513716  0.6601533      healthy
## 210 -0.99179758 -0.6971871 -0.89205619 -0.9739967      healthy
## 43  -0.99179758 -0.6971871  0.48639457 -0.9739967      healthy
## 112  1.01842302 -0.6971871 -0.89205619  0.6601533      healthy
## 201 -0.99179758  1.4295857 -0.89205619 -0.9739967      healthy
## 25  -0.99179758 -0.6971871  0.48639457  0.6601533      healthy
## 250 -0.99179758  1.4295857  0.40024139  0.6601533      healthy
## 5   -0.99179758 -0.6971871 -0.20283081 -0.9739967      healthy
## 192  1.01842302  1.4295857 -0.80590302  0.6601533 heartDisease
## 152  1.01842302 -0.6971871  0.48639457  0.6601533      healthy
## 288  1.01842302 -0.6971871 -0.89205619 -0.9739967      healthy
## 257  0.01331272 -0.6971871  0.05562870  0.6601533      healthy
## 63  -0.99179758 -0.6971871 -0.89205619 -0.9739967      healthy
## 253  1.01842302 -0.6971871 -0.37513716 -0.9739967      healthy
## 35  -0.99179758 -0.6971871 -0.89205619 -0.9739967      healthy
## 101  1.01842302 -0.6971871 -0.89205619 -0.9739967      healthy
## 244 -0.99179758 -0.6971871 -0.89205619 -0.9739967      healthy
## 143 -0.99179758  1.4295857  0.65870091  0.6601533 heartDisease
## 179  1.01842302 -0.6971871 -0.89205619 -0.9739967      healthy
## 199  1.01842302 -0.6971871 -0.89205619 -0.9739967 heartDisease
## 115 -0.99179758 -0.6971871 -0.89205619  0.6601533      healthy
## 77   1.01842302 -0.6971871  0.40024139 -0.9739967      healthy
## 275  1.01842302 -0.6971871 -0.37513716  0.6601533      healthy
## 218 -0.99179758 -0.6971871  0.83100726  0.6601533      healthy
## 122 -0.99179758  1.4295857  0.14178188  0.6601533      healthy
## 53   1.01842302 -0.6971871 -0.89205619 -0.9739967      healthy
## 37   1.01842302  1.4295857 -0.37513716  0.6601533 heartDisease
## 54  -0.99179758  1.4295857  0.31408822 -0.9739967 heartDisease
## 19  -0.99179758 -0.6971871 -0.37513716 -0.9739967      healthy
## 227 -0.99179758 -0.6971871 -0.89205619 -0.9739967      healthy
## 183  1.01842302 -0.6971871  2.72637706  2.2943034      healthy
## 18  -0.99179758 -0.6971871 -0.71974985 -0.9739967      healthy
## 98  -0.99179758 -0.6971871 -0.20283081 -0.9739967      healthy
## 190 -0.99179758 -0.6971871 -0.89205619 -0.9739967      healthy
## 56  -0.99179758 -0.6971871 -0.37513716  0.6601533 heartDisease
## 298 -0.99179758 -0.6971871  0.14178188  0.6601533 heartDisease
## 254 -0.99179758 -0.6971871  0.14178188  0.6601533      healthy
## 99   1.01842302 -0.6971871 -0.89205619 -0.9739967      healthy
## 28  -0.99179758 -0.6971871  0.40024139 -0.9739967      healthy
## 88   1.01842302 -0.6971871 -0.89205619 -0.9739967      healthy
## 159 -0.99179758 -0.6971871 -0.03052447 -0.9739967      healthy
## 271  1.01842302 -0.6971871  1.08946678 -0.9739967      healthy
## 202 -0.99179758 -0.6971871 -0.71974985 -0.9739967      healthy
## 225 -0.99179758 -0.6971871 -0.28898399 -0.9739967      healthy
## 196  1.01842302 -0.6971871 -0.80590302  0.6601533      healthy
## 116  1.01842302 -0.6971871 -0.89205619 -0.9739967      healthy
## 204 -0.99179758 -0.6971871 -0.89205619 -0.9739967      healthy
## 20   1.01842302  1.4295857  0.65870091  0.6601533      healthy
## 214 -0.99179758 -0.6971871 -0.89205619 -0.9739967 heartDisease
## 111  1.01842302  1.4295857  0.14178188  0.6601533 heartDisease
## 14  -0.99179758 -0.6971871 -0.46129033 -0.9739967      healthy
## 67   1.01842302 -0.6971871  0.48639457 -0.9739967      healthy
## 2    1.01842302  1.4295857  1.34792629  0.6601533 heartDisease
## 234 -0.99179758 -0.6971871 -0.89205619 -0.9739967      healthy
## 58   1.01842302 -0.6971871 -0.46129033  2.2943034      healthy
## 163  1.01842302 -0.6971871 -0.03052447  0.6601533      healthy
## 16  -0.99179758 -0.6971871 -0.03052447  2.2943034 heartDisease
## 74   1.01842302 -0.6971871 -0.89205619 -0.9739967 heartDisease
## 22   1.01842302 -0.6971871  0.65870091  0.6601533 heartDisease
## 171  1.01842302  1.4295857 -0.89205619 -0.9739967      healthy
## 294 -0.99179758  1.4295857 -0.89205619  0.6601533 heartDisease
## 81   1.01842302 -0.6971871 -0.54744350  0.6601533      healthy
## 173  1.01842302 -0.6971871  0.14178188  0.6601533      healthy
## 268 -0.99179758 -0.6971871 -0.89205619 -0.9739967 heartDisease
## 232  1.01842302 -0.6971871 -0.20283081 -0.9739967 heartDisease
## 219  1.01842302 -0.6971871 -0.89205619 -0.9739967      healthy
## 160 -0.99179758 -0.6971871 -0.89205619 -0.9739967      healthy
## 11   1.01842302 -0.6971871  0.22793505  0.6601533      healthy
## 95  -0.99179758  1.4295857 -0.89205619 -0.9739967 heartDisease
## 221  1.01842302 -0.6971871 -0.89205619 -0.9739967      healthy
## 239 -0.99179758 -0.6971871 -0.89205619 -0.9739967      healthy
## 209 -0.99179758  1.4295857  0.31408822  0.6601533 heartDisease
## 26  -0.99179758 -0.6971871 -0.89205619 -0.9739967      healthy
## 132  1.01842302 -0.6971871 -0.89205619 -0.9739967      healthy
## 78   1.01842302 -0.6971871 -0.71974985  0.6601533      healthy
## 262 -0.99179758 -0.6971871 -0.11667764 -0.9739967      healthy
## 7   -0.99179758  1.4295857 -0.37513716 -0.9739967      healthy
## 10  -0.99179758 -0.6971871 -0.54744350  0.6601533      healthy
## 4    1.01842302 -0.6971871  0.31408822 -0.9739967      healthy
## 255 -0.99179758 -0.6971871 -0.89205619  0.6601533      healthy
## 291 -0.99179758 -0.6971871  0.14178188 -0.9739967      healthy
## 168  1.01842302  1.4295857 -0.89205619 -0.9739967 heartDisease
## 39  -0.99179758  1.4295857 -0.03052447  0.6601533      healthy
## 185 -0.99179758 -0.6971871 -0.89205619 -0.9739967      healthy
## 237  1.01842302 -0.6971871 -0.20283081 -0.9739967 heartDisease
## 175 -0.99179758  1.4295857  0.14178188  0.6601533 heartDisease
## 3   -0.99179758 -0.6971871  2.12330485  2.2943034      healthy
## 162 -0.99179758 -0.6971871  0.48639457  0.6601533      healthy
## 80   1.01842302  1.4295857  1.69253898  0.6601533      healthy
## 86   1.01842302 -0.6971871 -0.89205619 -0.9739967      healthy
## 15  -0.99179758 -0.6971871  0.48639457 -0.9739967      healthy
## 247  1.01842302  1.4295857 -0.03052447  0.6601533 heartDisease
## 215  1.01842302 -0.6971871  0.74485409  0.6601533      healthy
## 131 -0.99179758  1.4295857 -0.89205619 -0.9739967      healthy
## 21   1.01842302 -0.6971871 -0.03052447 -0.9739967      healthy
## 167  1.01842302  1.4295857 -0.89205619 -0.9739967      healthy
## 44   1.01842302 -0.6971871 -0.89205619 -0.9739967 heartDisease
## 57   1.01842302 -0.6971871 -0.89205619 -0.9739967 heartDisease
## 69  -0.99179758 -0.6971871  2.20945802  0.6601533 heartDisease
## 249  1.01842302 -0.6971871 -0.89205619 -0.9739967      healthy
## 301  1.01842302 -0.6971871 -0.89205619  0.6601533 heartDisease
## 216 -0.99179758 -0.6971871 -0.89205619 -0.9739967      healthy
## 188  1.01842302 -0.6971871 -0.89205619 -0.9739967 heartDisease
## 259 -0.99179758 -0.6971871 -0.63359668 -0.9739967 heartDisease
## 62   1.01842302  1.4295857  1.00331360  0.6601533 heartDisease
## 164 -0.99179758 -0.6971871 -0.89205619 -0.9739967      healthy
## 30  -0.99179758 -0.6971871  0.65870091 -0.9739967      healthy
## 124  1.01842302 -0.6971871  0.31408822  0.6601533 heartDisease
## 133  1.01842302  1.4295857 -0.89205619 -0.9739967      healthy
## 194  1.01842302 -0.6971871  0.40024139  0.6601533      healthy
## 102  1.01842302 -0.6971871 -0.89205619 -0.9739967      healthy
## 151  1.01842302 -0.6971871 -0.37513716  0.6601533      healthy
## 230  1.01842302 -0.6971871 -0.80590302  0.6601533      healthy
## 84  -0.99179758 -0.6971871 -0.71974985 -0.9739967      healthy
## 242 -0.99179758 -0.6971871 -0.89205619 -0.9739967      healthy
## 147 -0.99179758 -0.6971871 -0.89205619 -0.9739967      healthy
## 217  1.01842302  1.4295857 -0.89205619  0.6601533      healthy
## 92  -0.99179758 -0.6971871  0.65870091  0.6601533      healthy
## 55   1.01842302  1.4295857  1.00331360  0.6601533 heartDisease
## 273 -0.99179758 -0.6971871  0.48639457  0.6601533      healthy
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{unique}\NormalTok{(data\_aprendizaje}\SpecialCharTok{$}\NormalTok{diagnosis)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "healthy"      "heartDisease"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data\_aprendizaje }\OtherTok{\textless{}{-}} \FunctionTok{na.omit}\NormalTok{(data\_aprendizaje)}
\NormalTok{data\_aprendizaje}\SpecialCharTok{$}\NormalTok{diagnosis[data\_aprendizaje}\SpecialCharTok{$}\NormalTok{diagnosis }\SpecialCharTok{==} \StringTok{"healthy"}\NormalTok{] }\OtherTok{\textless{}{-}} \DecValTok{0} 
\NormalTok{data\_aprendizaje}\SpecialCharTok{$}\NormalTok{diagnosis[data\_aprendizaje}\SpecialCharTok{$}\NormalTok{diagnosis }\SpecialCharTok{==} \StringTok{"heartDisease"}\NormalTok{] }\OtherTok{\textless{}{-}} \DecValTok{1}

\NormalTok{modelo }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(diagnosis }\SpecialCharTok{\textasciitilde{}}\NormalTok{ ., }\AttributeTok{data=}\NormalTok{data\_aprendizaje)}
\FunctionTok{summary}\NormalTok{(modelo)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = diagnosis ~ ., data = data_aprendizaje)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -0.6507 -0.2267 -0.1062  0.2813  0.8989 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(>|t|)    
## (Intercept)  0.330904   0.036586   9.045 1.02e-15 ***
## age         -0.002125   0.038060  -0.056  0.95554    
## sex          0.079327   0.034242   2.317  0.02195 *  
## cp           0.067070   0.034676   1.934  0.05507 .  
## trestbps     0.043246   0.035211   1.228  0.22140    
## chol         0.018541   0.034760   0.533  0.59460    
## fbs         -0.034381   0.037385  -0.920  0.35932    
## restecg      0.047029   0.033605   1.399  0.16386    
## exang        0.127944   0.040449   3.163  0.00191 ** 
## oldpeak     -0.006124   0.053256  -0.115  0.90862    
## slope        0.072070   0.043386   1.661  0.09889 .  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.4005 on 142 degrees of freedom
## Multiple R-squared:  0.2292, Adjusted R-squared:  0.1749 
## F-statistic: 4.222 on 10 and 142 DF,  p-value: 3.837e-05
\end{verbatim}

Las variables más relevantes son: sex, cp, exang y slope. Podría
considerar, realizar un modelado con estás variables, y comparar el
resultado con la anterior, veamos.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{modelo2 }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(diagnosis }\SpecialCharTok{\textasciitilde{}}\NormalTok{ sex }\SpecialCharTok{+}\NormalTok{ cp }\SpecialCharTok{+}\NormalTok{ exang }\SpecialCharTok{+}\NormalTok{ slope }\SpecialCharTok{+}\NormalTok{ chol, }\AttributeTok{data=}\NormalTok{data\_aprendizaje)}
\FunctionTok{summary}\NormalTok{(modelo2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = diagnosis ~ sex + cp + exang + slope + chol, data = data_aprendizaje)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -0.6872 -0.2367 -0.1298  0.3054  0.9170 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept)  0.33005    0.03467   9.521  < 2e-16 ***
## sex          0.07857    0.03285   2.392  0.01803 *  
## cp           0.06712    0.03411   1.968  0.05095 .  
## exang        0.12816    0.03979   3.221  0.00157 ** 
## slope        0.07752    0.03727   2.080  0.03924 *  
## chol         0.03206    0.03357   0.955  0.34116    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.3995 on 147 degrees of freedom
## Multiple R-squared:  0.2058, Adjusted R-squared:  0.1787 
## F-statistic: 7.616 on 5 and 147 DF,  p-value: 2.171e-06
\end{verbatim}

El r cuadrado ajustado es un poco mejor que usando todas las variables
disponibles. Veamos un poco más la validación de estos modelos.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Q{-}Q plot}
\FunctionTok{qqnorm}\NormalTok{(}\FunctionTok{rstandard}\NormalTok{(modelo))}
\FunctionTok{qqline}\NormalTok{(}\FunctionTok{rstandard}\NormalTok{(modelo), }\AttributeTok{lty =} \DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{methods-II_files/figure-latex/unnamed-chunk-34-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# frente a valores ajustados: comprobar que la nube sea dispersa}
\FunctionTok{plot}\NormalTok{(}\FunctionTok{rstandard}\NormalTok{(modelo) }\SpecialCharTok{\textasciitilde{}} \FunctionTok{fitted}\NormalTok{(modelo))}
\FunctionTok{abline}\NormalTok{(}\AttributeTok{h =} \DecValTok{0}\NormalTok{, }\AttributeTok{lty =} \DecValTok{2}\NormalTok{)}
\FunctionTok{abline}\NormalTok{(}\AttributeTok{h =} \FunctionTok{c}\NormalTok{(}\SpecialCharTok{{-}}\DecValTok{2}\NormalTok{, }\DecValTok{2}\NormalTok{), }\AttributeTok{lty =} \DecValTok{3}\NormalTok{, }\AttributeTok{col =} \DecValTok{4}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{methods-II_files/figure-latex/unnamed-chunk-34-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Comprobar si se rechaza la normalidad de los residuos}
\FunctionTok{shapiro.test}\NormalTok{(}\FunctionTok{rstandard}\NormalTok{(modelo))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Shapiro-Wilk normality test
## 
## data:  rstandard(modelo)
## W = 0.91525, p-value = 8.372e-08
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Varios gráficos de validación, incluye alguno de los resultados anteriores}
\FunctionTok{plot}\NormalTok{(modelo)}
\end{Highlighting}
\end{Shaded}

\includegraphics{methods-II_files/figure-latex/unnamed-chunk-34-3.pdf}
\includegraphics{methods-II_files/figure-latex/unnamed-chunk-34-4.pdf}
\includegraphics{methods-II_files/figure-latex/unnamed-chunk-34-5.pdf}
\includegraphics{methods-II_files/figure-latex/unnamed-chunk-34-6.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Lo realizado hasta aquí nos podría servir también para validar un modelo ANOVA,}
\CommentTok{\# por ejemplo para: \textquotesingle{}modelo \textless{}{-} aov(Sepal.Length \textasciitilde{} Species, data = iris)\textquotesingle{}}
\CommentTok{\# Comprobar si son dispersas las nubes de los residuos frente a las covariables}
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow =} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{))}
\FunctionTok{plot}\NormalTok{(}\FunctionTok{resid}\NormalTok{(modelo) }\SpecialCharTok{\textasciitilde{}}\NormalTok{ data\_aprendizaje}\SpecialCharTok{$}\NormalTok{diagnosis)}
\FunctionTok{plot}\NormalTok{(}\FunctionTok{resid}\NormalTok{(modelo) }\SpecialCharTok{\textasciitilde{}}\NormalTok{ data\_aprendizaje}\SpecialCharTok{$}\NormalTok{diagnosis)}
\end{Highlighting}
\end{Shaded}

\includegraphics{methods-II_files/figure-latex/unnamed-chunk-34-7.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow =} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{qqnorm}\NormalTok{(}\FunctionTok{rstandard}\NormalTok{(modelo2))}
\FunctionTok{qqline}\NormalTok{(}\FunctionTok{rstandard}\NormalTok{(modelo2), }\AttributeTok{lty =} \DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{methods-II_files/figure-latex/unnamed-chunk-35-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(}\FunctionTok{rstandard}\NormalTok{(modelo2) }\SpecialCharTok{\textasciitilde{}} \FunctionTok{fitted}\NormalTok{(modelo2))}
\FunctionTok{abline}\NormalTok{(}\AttributeTok{h =} \DecValTok{0}\NormalTok{, }\AttributeTok{lty =} \DecValTok{2}\NormalTok{)}
\FunctionTok{abline}\NormalTok{(}\AttributeTok{h =} \FunctionTok{c}\NormalTok{(}\SpecialCharTok{{-}}\DecValTok{2}\NormalTok{, }\DecValTok{2}\NormalTok{), }\AttributeTok{lty =} \DecValTok{3}\NormalTok{, }\AttributeTok{col =} \DecValTok{4}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{methods-II_files/figure-latex/unnamed-chunk-35-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Comprobar si se rechaza la normalidad de los residuos}
\FunctionTok{shapiro.test}\NormalTok{(}\FunctionTok{rstandard}\NormalTok{(modelo2))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Shapiro-Wilk normality test
## 
## data:  rstandard(modelo2)
## W = 0.89528, p-value = 5.569e-09
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Varios gráficos de validación, incluye alguno de los resultados anteriores}
\FunctionTok{plot}\NormalTok{(modelo2)}
\end{Highlighting}
\end{Shaded}

\includegraphics{methods-II_files/figure-latex/unnamed-chunk-35-3.pdf}
\includegraphics{methods-II_files/figure-latex/unnamed-chunk-35-4.pdf}
\includegraphics{methods-II_files/figure-latex/unnamed-chunk-35-5.pdf}
\includegraphics{methods-II_files/figure-latex/unnamed-chunk-35-6.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Lo realizado hasta aquí nos podría servir también para validar un modelo ANOVA,}
\CommentTok{\# por ejemplo para: \textquotesingle{}modelo \textless{}{-} aov(Sepal.Length \textasciitilde{} Species, data = iris)\textquotesingle{}}
\CommentTok{\# Comprobar si son dispersas las nubes de los residuos frente a las covariables}
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow =} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{))}
\FunctionTok{plot}\NormalTok{(}\FunctionTok{resid}\NormalTok{(modelo2) }\SpecialCharTok{\textasciitilde{}}\NormalTok{ data\_aprendizaje}\SpecialCharTok{$}\NormalTok{diagnosis)}
\FunctionTok{plot}\NormalTok{(}\FunctionTok{resid}\NormalTok{(modelo2) }\SpecialCharTok{\textasciitilde{}}\NormalTok{ data\_aprendizaje}\SpecialCharTok{$}\NormalTok{diagnosis)}
\end{Highlighting}
\end{Shaded}

\includegraphics{methods-II_files/figure-latex/unnamed-chunk-35-7.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow =} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\hypertarget{anuxe1lisis-de-componentes-principales}{%
\section{Análisis de componentes
principales}\label{anuxe1lisis-de-componentes-principales}}

Tiendo en cuenta que el segundo modelo podría funcionar mejor que el
primero, teniendo menos variables, vamos a realizar un análisis de las
componentes principales en el dataset. Este análisis nos permite
entender la varianza en función de la cantidad de variables.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{head}\NormalTok{(data2, }\DecValTok{4}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##          age        sex         cp    trestbps        chol        fbs
## 2  1.3926081  0.6867343  0.8750283 -0.66122880 -0.34206509 -0.4122838
## 3 -1.9259163  0.6867343 -0.1736167 -0.09344064  0.06289604 -0.4122838
## 4 -1.4834463 -1.4513456 -1.2222618 -0.09344064 -0.82416167 -0.4122838
## 5  0.1758159  0.6867343 -1.2222618 -0.66122880 -0.20707804 -0.4122838
##      restecg      exang    oldpeak      slope    diagnosis
## 2  1.0184230  1.4295857  1.3479263  0.6601533 heartDisease
## 3 -0.9917976 -0.6971871  2.1233048  2.2943034      healthy
## 4  1.0184230 -0.6971871  0.3140882 -0.9739967      healthy
## 5 -0.9917976 -0.6971871 -0.2028308 -0.9739967      healthy
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{X }\OtherTok{\textless{}{-}} \FunctionTok{as.matrix}\NormalTok{(data2[, }\SpecialCharTok{{-}}\DecValTok{11}\NormalTok{])}
\NormalTok{p }\OtherTok{\textless{}{-}} \FunctionTok{ncol}\NormalTok{(X)}
\NormalTok{S }\OtherTok{\textless{}{-}} \FunctionTok{cov}\NormalTok{(X)}
\NormalTok{var\_tot }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{(}\FunctionTok{diag}\NormalTok{(S))}
\NormalTok{var\_tot}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 9.062984
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{acp\_cov }\OtherTok{\textless{}{-}} \FunctionTok{prcomp}\NormalTok{(data2[,}\SpecialCharTok{{-}}\DecValTok{11}\NormalTok{])}
\NormalTok{acp\_cov}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Standard deviations (1, .., p=10):
##  [1] 1.2922894 1.1607314 1.1298379 0.9780670 0.9481158 0.8842278 0.8322954
##  [8] 0.7776518 0.7274873 0.5523115
## 
## Rotation (n x k) = (10 x 10):
##                 PC1        PC2         PC3         PC4         PC5         PC6
## age      -0.5971503  0.1223762 -0.06656082  0.09822951 -0.36945685  0.05449890
## sex       0.2369251 -0.4852210 -0.46173620 -0.42059796 -0.19845768 -0.28022250
## cp       -0.1466008 -0.3433659  0.61960246 -0.33250880 -0.23457267  0.12230020
## trestbps -0.3224536  0.1477036 -0.37086230 -0.05319924 -0.34109014 -0.39464085
## chol     -0.4183760  0.3130329  0.14650054 -0.27916502  0.11367553 -0.14370663
## fbs      -0.0628277 -0.0164395 -0.36326901 -0.13301207 -0.25670730  0.83371122
## restecg  -0.3567639 -0.1169681 -0.21153350 -0.43834587  0.69996268  0.09868370
## exang    -0.1848044 -0.4348100  0.21572602 -0.12896949 -0.17194084 -0.04316852
## oldpeak  -0.2138337 -0.3101548 -0.09351348  0.25796261  0.02206816 -0.12711013
## slope    -0.2750747 -0.4611626 -0.08641528  0.57367744  0.23222873  0.06573817
##                  PC7         PC8         PC9         PC10
## age       0.02843524 -0.67633492  0.08160798 -0.099951956
## sex       0.33909332 -0.20786888 -0.14253946 -0.147995670
## cp       -0.19371231  0.02779644 -0.50773694 -0.007945672
## trestbps -0.46664748  0.46458641 -0.15762166 -0.057527518
## chol      0.69381370  0.32616120 -0.06252127 -0.048323647
## fbs       0.08662427  0.26424528 -0.02742178  0.084092338
## restecg  -0.31838696 -0.13890482  0.02475740  0.034358522
## exang    -0.03453002  0.23390409  0.79066621 -0.033661224
## oldpeak   0.14291084  0.02233493 -0.11905740  0.855013849
## slope     0.13059682  0.17898942 -0.21396201 -0.471132014
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(acp\_cov)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Importance of components:
##                           PC1    PC2    PC3    PC4     PC5     PC6     PC7
## Standard deviation     1.2923 1.1607 1.1298 0.9781 0.94812 0.88423 0.83230
## Proportion of Variance 0.1843 0.1487 0.1409 0.1056 0.09919 0.08627 0.07643
## Cumulative Proportion  0.1843 0.3329 0.4738 0.5793 0.67852 0.76479 0.84122
##                            PC8    PC9    PC10
## Standard deviation     0.77765 0.7275 0.55231
## Proportion of Variance 0.06673 0.0584 0.03366
## Cumulative Proportion  0.90795 0.9663 1.00000
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(acp\_cov, }\AttributeTok{type =} \StringTok{"l"}\NormalTok{, }\AttributeTok{pch =} \DecValTok{19}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{methods-II_files/figure-latex/unnamed-chunk-38-1.pdf}

No es claro que hay un codo, es decir, no hay un punto donde la varianza
deja de decrecer considerablemente. Veamos como se ven las primeras dos
componentes.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{head}\NormalTok{(acp\_cov}\SpecialCharTok{$}\NormalTok{x)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##          PC1        PC2        PC3        PC4          PC5         PC6
## 2 -1.8446412 -2.5218587  0.4101156 -0.1557217 -0.008631438 -0.12981533
## 3  0.4331331 -2.1914902 -0.4172831  2.0166825  0.670978326 -0.81888758
## 4  0.7559271  0.8157130 -0.2128147  0.3329052  1.685129965  0.01708491
## 5  1.0242843  0.4860856 -0.5359432  0.2023855 -0.506886799 -0.48890218
## 7 -1.1640053  0.6579306  2.5516836 -0.5388203 -0.726217129 -0.02414817
## 9 -1.7956861 -3.6343288 -1.1908646  0.4439153 -0.218221396  1.82157113
##           PC7        PC8        PC9      PC10
## 2  0.07938283 -1.1863987  0.5182864 0.7167190
## 3  1.24185623  1.5163380 -1.5082060 0.9000921
## 4 -1.20830228  0.4384188  0.3850201 1.2854548
## 5  0.82314053 -0.9230724  0.2783585 0.2949843
## 7  1.17571472  0.7406415  1.0870897 0.2548157
## 9 -0.32232938  1.2749153 -0.2342689 0.6667828
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cov}\NormalTok{(acp\_cov}\SpecialCharTok{$}\NormalTok{x[, }\DecValTok{1}\SpecialCharTok{:}\DecValTok{2}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##               PC1           PC2
## PC1  1.670012e+00 -2.153619e-16
## PC2 -2.153619e-16  1.347297e+00
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Para interpretar}
\NormalTok{acp\_cov}\SpecialCharTok{$}\NormalTok{rotation[, }\DecValTok{1}\SpecialCharTok{:}\DecValTok{2}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                 PC1        PC2
## age      -0.5971503  0.1223762
## sex       0.2369251 -0.4852210
## cp       -0.1466008 -0.3433659
## trestbps -0.3224536  0.1477036
## chol     -0.4183760  0.3130329
## fbs      -0.0628277 -0.0164395
## restecg  -0.3567639 -0.1169681
## exang    -0.1848044 -0.4348100
## oldpeak  -0.2138337 -0.3101548
## slope    -0.2750747 -0.4611626
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cor}\NormalTok{(data2[, }\SpecialCharTok{{-}}\DecValTok{11}\NormalTok{], acp\_cov}\SpecialCharTok{$}\NormalTok{x[, }\DecValTok{1}\SpecialCharTok{:}\DecValTok{2}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                  PC1         PC2
## age      -0.75694087  0.13933086
## sex       0.29566664 -0.54387959
## cp       -0.18807825 -0.39566845
## trestbps -0.43846571  0.18039789
## chol     -0.55336407  0.37188285
## fbs      -0.08832451 -0.02075825
## restecg  -0.46045842 -0.13559660
## exang    -0.27037351 -0.57137757
## oldpeak  -0.37645840 -0.49044620
## slope    -0.37218251 -0.56044283
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{diag }\OtherTok{\textless{}{-}} \FunctionTok{cbind}\NormalTok{(data2, acp\_cov}\SpecialCharTok{$}\NormalTok{x[, }\DecValTok{1}\SpecialCharTok{:}\DecValTok{2}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(diag, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ PC1, }\AttributeTok{y =}\NormalTok{ data2}\SpecialCharTok{$}\NormalTok{diagnosis)) }\SpecialCharTok{+} \FunctionTok{geom\_point}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{methods-II_files/figure-latex/unnamed-chunk-42-1.pdf}

Con una componente no es clara la utilidad de las componentes.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(diag, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ PC1, }\AttributeTok{y =}\NormalTok{ PC2, }\AttributeTok{color =}\NormalTok{ data2}\SpecialCharTok{$}\NormalTok{diagnosis)) }\SpecialCharTok{+} \FunctionTok{geom\_point}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{methods-II_files/figure-latex/unnamed-chunk-43-1.pdf}

Dos componentes no permiten ver claramente la diferencia entre las dos
categorías. Por otro lado, el biplot nos sirve para resumir las
relaciones entre variables, entre objetos y entre variables y objetos.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{biplot}\NormalTok{(acp\_cov, }\AttributeTok{scale =} \DecValTok{0}\NormalTok{, }\AttributeTok{cex =} \FloatTok{0.6}\NormalTok{, }\AttributeTok{col =} \FunctionTok{c}\NormalTok{(}\StringTok{"blue4"}\NormalTok{, }\StringTok{"brown3"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{methods-II_files/figure-latex/unnamed-chunk-44-1.pdf}

En este caso la dispersión de las variables no permite ver las
diferentes contribuciones a las primeras dos componentes principales.
Esto podría deberse a la poca diferencia de varianza entre las
variables.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(acp\_cov, }\AttributeTok{main=}\StringTok{"Varianza de las componentes"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{methods-II_files/figure-latex/unnamed-chunk-45-1.pdf}

Podríamos ver de manera más clara como se está acumulando la varianza en
las componentes principales.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{prop\_varianza }\OtherTok{\textless{}{-}}\NormalTok{ acp\_cov}\SpecialCharTok{$}\NormalTok{sdev}\SpecialCharTok{\^{}}\DecValTok{2}\SpecialCharTok{/}\FunctionTok{sum}\NormalTok{(acp\_cov}\SpecialCharTok{$}\NormalTok{sdev}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}
\NormalTok{prop\_varianza\_acum }\OtherTok{\textless{}{-}} \FunctionTok{cumsum}\NormalTok{(prop\_varianza)}
\FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data =} \FunctionTok{data.frame}\NormalTok{(prop\_varianza\_acum, }\AttributeTok{pc =} \FunctionTok{factor}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\DecValTok{10}\NormalTok{)),}
       \FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ pc, }\AttributeTok{y =}\NormalTok{ prop\_varianza\_acum, }\AttributeTok{group =} \DecValTok{1}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{geom\_line}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{geom\_label}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{label =} \FunctionTok{round}\NormalTok{(prop\_varianza\_acum,}\DecValTok{2}\NormalTok{))) }\SpecialCharTok{+}
  \FunctionTok{theme\_bw}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{x =} \StringTok{"Componentes principales"}\NormalTok{, }
       \AttributeTok{y =} \StringTok{"Prop. varianza explicada acumulada"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{methods-II_files/figure-latex/unnamed-chunk-46-1.pdf}

Debido a la poca acumulación de varianza en las primeras componentes, se
tiene mas de un cincuenta por ciento de la varianza en las primeras
cuatro componentes principales.

\hypertarget{anuxe1lisis-factorial}{%
\section{Análisis factorial}\label{anuxe1lisis-factorial}}

El objetivo de este análisis será identificar las variables más
relevantes que influyen en la presencia de enfermedades cardíacas en los
pacientes. Para ello, utilizaremos técnicas de extracción de factores
para encontrar patrones en las variables y reducir el número de
dimensiones a unas pocas variables latentes que expliquen la mayor
cantidad de variabilidad en los datos.

Una vez identificados los factores, trataremos de utilizar esta
información para entender mejor la relación entre las diferentes
variables y cómo influyen en la presencia de enfermedades cardíacas.
Este análisis puede proporcionar información valiosa para mejorar la
prevención de las enfermedades cardíacas en la población en general.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{X }\OtherTok{\textless{}{-}}\NormalTok{ data2[, }\SpecialCharTok{{-}}\DecValTok{11}\NormalTok{]}
\NormalTok{p }\OtherTok{\textless{}{-}} \FunctionTok{ncol}\NormalTok{(X)}
\NormalTok{R }\OtherTok{\textless{}{-}} \FunctionTok{cor}\NormalTok{(X)}
\NormalTok{R}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                  age          sex           cp     trestbps        chol
## age       1.00000000 -0.163432687  0.050575884  0.273128928  0.26635906
## sex      -0.16343269  1.000000000 -0.057750481  0.009796596 -0.20175523
## cp        0.05057588 -0.057750481  1.000000000 -0.123978825  0.05473986
## trestbps  0.27312893  0.009796596 -0.123978825  1.000000000  0.12422507
## chol      0.26635906 -0.201755233  0.054739856  0.124225072  1.00000000
## fbs       0.09493798  0.107216792 -0.095249101  0.089084144 -0.02442318
## restecg   0.13282122  0.028084103  0.008991095  0.112919434  0.15959783
## exang     0.08467163  0.087853366  0.321841882 -0.005984348  0.01353542
## oldpeak   0.19244721  0.124366784  0.046156375  0.103255229  0.01837994
## slope     0.12292514  0.002538958  0.032531637  0.011867156 -0.04631952
##                  fbs     restecg        exang     oldpeak        slope
## age       0.09493798 0.132821217  0.084671627  0.19244721  0.122925139
## sex       0.10721679 0.028084103  0.087853366  0.12436678  0.002538958
## cp       -0.09524910 0.008991095  0.321841882  0.04615638  0.032531637
## trestbps  0.08908414 0.112919434 -0.005984348  0.10325523  0.011867156
## chol     -0.02442318 0.159597830  0.013535421  0.01837994 -0.046319517
## fbs       1.00000000 0.060750658 -0.024755672 -0.01822332  0.026053009
## restecg   0.06075066 1.000000000  0.068873181  0.09720714  0.124386145
## exang    -0.02475567 0.068873181  1.000000000  0.20378952  0.189492983
## oldpeak  -0.01822332 0.097207141  0.203789524  1.00000000  0.494716139
## slope     0.02605301 0.124386145  0.189492983  0.49471614  1.000000000
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Valores{-}vectores propios.}
\NormalTok{Rprop }\OtherTok{\textless{}{-}} \FunctionTok{eigen}\NormalTok{(R)}
\NormalTok{Rprop}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## eigen() decomposition
## $values
##  [1] 1.8720076 1.5059094 1.3396869 1.0514315 0.9237600 0.8859567 0.7295919
##  [8] 0.6346055 0.6015982 0.4554524
## 
## $vectors
##              [,1]       [,2]        [,3]        [,4]        [,5]         [,6]
##  [1,] -0.41924663  0.3892483  0.04173529  0.01372482 -0.31443425  0.017344521
##  [2,]  0.01267321 -0.3701168 -0.42761127  0.41579825  0.12600819 -0.379037726
##  [3,] -0.17297998 -0.2298205  0.57590161  0.34622434 -0.13296337  0.042981972
##  [4,] -0.24599512  0.3756667 -0.29061473  0.11410029 -0.24796977 -0.561414922
##  [5,] -0.22013478  0.4729146  0.28262233  0.05112064  0.20037521  0.002057875
##  [6,] -0.05789928  0.1110591 -0.42014376  0.47449695 -0.30596770  0.656496490
##  [7,] -0.29198802  0.1596544 -0.09110947  0.27348778  0.80661532  0.111026474
##  [8,] -0.34667248 -0.3306566  0.28345580  0.37937347 -0.13904240 -0.129309010
##  [9,] -0.50990452 -0.2555867 -0.17870536 -0.30610392 -0.02855221 -0.067374594
## [10,] -0.46516975 -0.2853527 -0.14935623 -0.39224125  0.03926868  0.272793869
##               [,7]        [,8]       [,9]       [,10]
##  [1,] -0.003788003  0.47797939 -0.5694229 -0.13746629
##  [2,] -0.438817858  0.26867397 -0.0688809 -0.27941785
##  [3,]  0.114059627  0.44442106  0.4819408 -0.05842199
##  [4,]  0.352505624 -0.17383357  0.4067445 -0.06549789
##  [5,] -0.692443903 -0.25716848  0.2138981 -0.11782489
##  [6,] -0.057170380 -0.10305163  0.1733501  0.11875690
##  [7,]  0.345958091  0.09720742 -0.0629649  0.10050346
##  [8,]  0.078698306 -0.59413410 -0.3830294  0.06526196
##  [9,] -0.235040104  0.13073275  0.1431516  0.67145792
## [10,]  0.079268153 -0.12381794  0.1622768 -0.63413237
\end{verbatim}

Porcentajes acumulados de varianza.

\begin{Shaded}
\begin{Highlighting}[]
\DecValTok{100}\SpecialCharTok{*}\FunctionTok{cumsum}\NormalTok{(Rprop}\SpecialCharTok{$}\NormalTok{values)}\SpecialCharTok{/}\NormalTok{p}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1]  18.72008  33.77917  47.17604  57.69035  66.92795  75.78752  83.08344
##  [8]  89.42949  95.44548 100.00000
\end{verbatim}

Al igual que en los componentes principales, para tener más de cincuenta
por ciento de la varianza hay que tomar los primeros cuatro factores.
Ahora, elegimos el número de factores y obtenemos la estimación de la
matriz de cargas.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{m }\OtherTok{\textless{}{-}} \DecValTok{3}
\FunctionTok{sum}\NormalTok{(Rprop}\SpecialCharTok{$}\NormalTok{values[(m }\SpecialCharTok{+} \DecValTok{1}\NormalTok{)}\SpecialCharTok{:}\NormalTok{p]) }\CommentTok{\# cota de la suma de cuadrados de la matriz residual}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 5.282396
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{L }\OtherTok{\textless{}{-}}\NormalTok{ (}\FunctionTok{rep}\NormalTok{(}\DecValTok{1}\NormalTok{, p) }\SpecialCharTok{\%*\%} \FunctionTok{t}\NormalTok{(}\FunctionTok{sqrt}\NormalTok{(Rprop}\SpecialCharTok{$}\NormalTok{values[}\DecValTok{1}\SpecialCharTok{:}\NormalTok{m]))) }\SpecialCharTok{*}\NormalTok{ Rprop}\SpecialCharTok{$}\NormalTok{vectors[, }\DecValTok{1}\SpecialCharTok{:}\NormalTok{m]}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{h2 }\OtherTok{\textless{}{-}} \FunctionTok{rowSums}\NormalTok{(L}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}
\NormalTok{h2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] 0.5595388 0.4515534 0.5798768 0.4389499 0.5345182 0.2613322 0.2091074
##  [8] 0.4972681 0.6278835 0.5575756
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{psi }\OtherTok{\textless{}{-}} \DecValTok{1} \SpecialCharTok{{-}}\NormalTok{ h2}
\NormalTok{psi}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] 0.4404612 0.5484466 0.4201232 0.5610501 0.4654818 0.7386678 0.7908926
##  [8] 0.5027319 0.3721165 0.4424244
\end{verbatim}

Estimamos la matriz de correlaciones.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Rbarra }\OtherTok{\textless{}{-}}\NormalTok{ L }\SpecialCharTok{\%*\%}\FunctionTok{t}\NormalTok{(L) }\SpecialCharTok{+} \FunctionTok{diag}\NormalTok{(psi)}
\NormalTok{Rbarra}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##              [,1]        [,2]        [,3]        [,4]        [,5]        [,6]
##  [1,]  1.00000000 -0.25080738  0.03324582  0.39702167  0.46578067  0.08704992
##  [2,] -0.25080738  1.00000000 -0.20592455 -0.04873544 -0.43071183  0.17741194
##  [3,]  0.03324582 -0.20592455  1.00000000 -0.27457331  0.12566453 -0.34384001
##  [4,]  0.39702167 -0.04873544 -0.27457331  1.00000000  0.25887621  0.25306699
##  [5,]  0.46578067 -0.43071183  0.12566453  0.25887621  1.00000000 -0.05612457
##  [6,]  0.08704992  0.17741194 -0.34384001  0.25306699 -0.05612457  1.00000000
##  [7,]  0.31765274 -0.04371915 -0.03099660  0.26025347  0.19953070  0.10963135
##  [8,]  0.09410674  0.01368898  0.44539003 -0.13777335  0.01470265 -0.17727181
##  [9,]  0.24038006  0.23273134  0.11569676  0.15979877 -0.03955413  0.11310816
## [10,]  0.18946373  0.23356997  0.13415608  0.11093243 -0.06807505  0.08676176
##              [,7]        [,8]        [,9]       [,10]
##  [1,]  0.31765274  0.09410674  0.24038006  0.18946373
##  [2,] -0.04371915  0.01368898  0.23273134  0.23356997
##  [3,] -0.03099660  0.44539003  0.11569676  0.13415608
##  [4,]  0.26025347 -0.13777335  0.15979877  0.11093243
##  [5,]  0.19953070  0.01470265 -0.03955413 -0.06807505
##  [6,]  0.10963135 -0.17727181  0.11310816  0.08676176
##  [7,]  1.00000000  0.07539624  0.23907872  0.20388774
##  [8,]  0.07539624  1.00000000  0.39031916  0.38725420
##  [9,]  0.23907872  0.39031916  1.00000000  0.58961230
## [10,]  0.20388774  0.38725420  0.58961230  1.00000000
\end{verbatim}

Se puede observar que algunas variables están moderadamente
correlacionadas, mientras que otras tienen una correlación más débil.
Por ejemplo, la presión arterial (trestbps) y el colesterol (chol)
tienen una correlación moderada positiva de 0.26, mientras que el sexo
(sex) y y el colesterol (chol) tienen una correlación negativa moderada
de -0.43. La correlación más fuerte es de 0.58, que se da entre la
variable que mide la lesión al miocardio (oldpeak: Depresión del ST) y
la pendiente del segmento ST (slope). Veamos la matriz residual.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{head}\NormalTok{(data2,}\DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         age        sex         cp    trestbps        chol        fbs    restecg
## 2  1.392608  0.6867343  0.8750283 -0.66122880 -0.34206509 -0.4122838  1.0184230
## 3 -1.925916  0.6867343 -0.1736167 -0.09344064  0.06289604 -0.4122838 -0.9917976
## 4 -1.483446 -1.4513456 -1.2222618 -0.09344064 -0.82416167 -0.4122838  1.0184230
##        exang   oldpeak      slope    diagnosis
## 2  1.4295857 1.3479263  0.6601533 heartDisease
## 3 -0.6971871 2.1233048  2.2943034      healthy
## 4 -0.6971871 0.3140882 -0.9739967      healthy
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{D }\OtherTok{\textless{}{-}}\NormalTok{ R }\SpecialCharTok{{-}}\NormalTok{ Rbarra}
\FunctionTok{sum}\NormalTok{(D}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.287301
\end{verbatim}

Ahora, la representación gráfica de las cargas en el espacio de los
factores.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{L }\OtherTok{\textless{}{-}} \FunctionTok{as.data.frame}\NormalTok{(L)}
\FunctionTok{rownames}\NormalTok{(L) }\OtherTok{\textless{}{-}} \FunctionTok{colnames}\NormalTok{(X)}
\FunctionTok{colnames}\NormalTok{(L) }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"F1"}\NormalTok{, }\StringTok{"F2"}\NormalTok{)}
\FunctionTok{ggplot}\NormalTok{(L, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ F1, }\AttributeTok{y =}\NormalTok{ F2, }\AttributeTok{label =} \FunctionTok{rownames}\NormalTok{(L))) }\SpecialCharTok{+}
\FunctionTok{geom\_hline}\NormalTok{(}\AttributeTok{yintercept =} \DecValTok{0}\NormalTok{, }\AttributeTok{lty =} \DecValTok{2}\NormalTok{) }\SpecialCharTok{+}
\FunctionTok{geom\_vline}\NormalTok{(}\AttributeTok{xintercept =} \DecValTok{0}\NormalTok{, }\AttributeTok{lty =} \DecValTok{2}\NormalTok{) }\SpecialCharTok{+}
\FunctionTok{geom\_text}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{methods-II_files/figure-latex/unnamed-chunk-56-1.pdf}

No es claro que algunas variables carguen mas en uno de los factores,
con excepción la variable sexo, parece tener una carga considerable en
el factor dos.

Realizamos una rotación de factores:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{vmax\_L }\OtherTok{\textless{}{-}} \FunctionTok{varimax}\NormalTok{(}\FunctionTok{as.matrix}\NormalTok{(L))}
\NormalTok{vmax\_L}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $loadings
## 
## Loadings:
##          F1     F2     <NA>  
## age      -0.232  0.706       
## sex      -0.328 -0.501 -0.304
## cp       -0.177         0.736
## trestbps -0.134  0.462 -0.455
## chol      0.113  0.712  0.121
## fbs      -0.116        -0.497
## restecg  -0.262  0.346 -0.143
## exang    -0.518         0.478
## oldpeak  -0.788              
## slope    -0.746              
## 
##                   F1    F2  <NA>
## SS loadings    1.752 1.603 1.362
## Proportion Var 0.175 0.160 0.136
## Cumulative Var 0.175 0.336 0.472
## 
## $rotmat
##           [,1]       [,2]        [,3]
## [1,] 0.8358418 -0.5455560 -0.06113173
## [2,] 0.4938234  0.7958447 -0.35038515
## [3,] 0.2398061  0.2626783  0.93460856
\end{verbatim}

Realizamos una representación gráfica de las cargas en el espacio de los
factores rotados.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Lstar }\OtherTok{\textless{}{-}} \FunctionTok{as.data.frame}\NormalTok{(vmax\_L}\SpecialCharTok{$}\NormalTok{loadings[, }\DecValTok{1}\SpecialCharTok{:}\NormalTok{m])}
\FunctionTok{rownames}\NormalTok{(Lstar) }\OtherTok{\textless{}{-}} \FunctionTok{colnames}\NormalTok{(X)}
\FunctionTok{colnames}\NormalTok{(Lstar) }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"F1"}\NormalTok{, }\StringTok{"F2"}\NormalTok{)}
\FunctionTok{ggplot}\NormalTok{(Lstar, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ F1, }\AttributeTok{y =}\NormalTok{ F2, }\AttributeTok{label =} \FunctionTok{rownames}\NormalTok{(Lstar))) }\SpecialCharTok{+}
\FunctionTok{geom\_hline}\NormalTok{(}\AttributeTok{yintercept =} \DecValTok{0}\NormalTok{, }\AttributeTok{lty =} \DecValTok{2}\NormalTok{) }\SpecialCharTok{+}
\FunctionTok{geom\_vline}\NormalTok{(}\AttributeTok{xintercept =} \DecValTok{0}\NormalTok{, }\AttributeTok{lty =} \DecValTok{2}\NormalTok{) }\SpecialCharTok{+}
\FunctionTok{geom\_text}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{methods-II_files/figure-latex/unnamed-chunk-58-1.pdf}

Con los factores rotados se ve una incidencia más fuerte de la depresión
del ST inducida por el ejercicio en relación con el reposo (oldpeak),
angina inducida por el ejercicio (exang), pendiente del segmento ST
(slope) y en menor medida, el tipo de dolor en el pecho (cp) y el azúcar
en sangre en ayunas (fbs). Por otro lado veamos que, sin rotaciones
funciona mejor el análisis y aumentar el número de factores no mejora de
manera considerable.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{diagnosis\_af }\OtherTok{\textless{}{-}} \FunctionTok{principal}\NormalTok{(data2[, }\SpecialCharTok{{-}}\NormalTok{(}\DecValTok{11}\NormalTok{)], }\AttributeTok{nfactors =} \DecValTok{4}\NormalTok{)}
\NormalTok{diagnosis\_af}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Principal Components Analysis
## Call: principal(r = data2[, -(11)], nfactors = 4)
## Standardized loadings (pattern matrix) based upon correlation matrix
##            RC2   RC1   RC3   RC4   h2   u2 com
## age       0.71  0.18  0.04 -0.16 0.56 0.44 1.2
## sex      -0.21  0.10  0.07  0.76 0.63 0.37 1.2
## cp       -0.01 -0.06  0.82 -0.15 0.71 0.29 1.1
## trestbps  0.60  0.07 -0.23  0.18 0.45 0.55 1.5
## chol      0.61 -0.15  0.11 -0.36 0.54 0.46 1.9
## fbs       0.31 -0.12 -0.10  0.62 0.50 0.50 1.6
## restecg   0.47  0.08  0.13  0.20 0.29 0.71 1.6
## exang     0.07  0.23  0.75  0.15 0.65 0.35 1.3
## oldpeak   0.13  0.84  0.08  0.05 0.73 0.27 1.1
## slope     0.04  0.85  0.05 -0.02 0.72 0.28 1.0
## 
##                        RC2  RC1  RC3  RC4
## SS loadings           1.61 1.56 1.36 1.23
## Proportion Var        0.16 0.16 0.14 0.12
## Cumulative Var        0.16 0.32 0.45 0.58
## Proportion Explained  0.28 0.27 0.24 0.21
## Cumulative Proportion 0.28 0.55 0.79 1.00
## 
## Mean item complexity =  1.4
## Test of the hypothesis that 4 components are sufficient.
## 
## The root mean square of the residuals (RMSR) is  0.11 
##  with the empirical chi square  256.76  with prob <  1.1e-48 
## 
## Fit based upon off diagonal values = 0.35
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{fa.diagram}\NormalTok{(diagnosis\_af)}
\end{Highlighting}
\end{Shaded}

\includegraphics{methods-II_files/figure-latex/unnamed-chunk-60-1.pdf}

Si tomamos cuatro componentes, en la primera aparecen la depresión del
ST inducida por el ejercicio (oldpeak) y la pendiente del segmento ST
(slope), que como y mencionamos estás muy correlacionadas. Pero en
general no permiten ver una incidencia de ciertas variables en los
factores.

\hypertarget{anuxe1lisis-de-conglomerados}{%
\section{Análisis de conglomerados}\label{anuxe1lisis-de-conglomerados}}

El análisis de conglomerados es una técnica de modelado de datos que se
utiliza para agrupar objetos similares en grupos o clusters.

\hypertarget{kmeans}{%
\subsection{Kmeans}\label{kmeans}}

Entre los métodos de análisis de conglomerados, el algoritmo k-means es
uno de los más populares y amplia mente utilizados. El algoritmo k-means
es una técnica de particionamiento que busca dividir los datos en k
clústeres, de tal manera que las observaciones dentro de cada clúster
sean lo más similares posible entre sí y lo más diferentes posible de
las observaciones en otros clústeres. En esta sección, se explorará el
uso del algoritmo k-means. Seleccionamos K = 2 casos como centroides
iniciales ya que se conoce que hay dos categorías.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{head}\NormalTok{(data2, }\DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         age        sex         cp    trestbps        chol        fbs    restecg
## 2  1.392608  0.6867343  0.8750283 -0.66122880 -0.34206509 -0.4122838  1.0184230
## 3 -1.925916  0.6867343 -0.1736167 -0.09344064  0.06289604 -0.4122838 -0.9917976
## 4 -1.483446 -1.4513456 -1.2222618 -0.09344064 -0.82416167 -0.4122838  1.0184230
##        exang   oldpeak      slope    diagnosis
## 2  1.4295857 1.3479263  0.6601533 heartDisease
## 3 -0.6971871 2.1233048  2.2943034      healthy
## 4 -0.6971871 0.3140882 -0.9739967      healthy
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{datos\_km }\OtherTok{\textless{}{-}} \FunctionTok{kmeans}\NormalTok{(data2[, }\DecValTok{1}\SpecialCharTok{:}\DecValTok{10}\NormalTok{], }\DecValTok{2}\NormalTok{, }\AttributeTok{nstart =} \FloatTok{1e3}\NormalTok{)}
\NormalTok{datos\_km}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## K-means clustering with 2 clusters of sizes 137, 81
## 
## Cluster means:
##           age        sex         cp    trestbps       chol           fbs
## 1 -0.25696494  0.6867343 -0.2807775 -0.07561955 -0.1979288  0.0008207375
## 2  0.08704875 -1.4513456 -0.1606705 -0.09484258  0.2090725 -0.2026714936
##       restecg      exang    oldpeak      slope
## 1 -0.05271642 -0.1693749 -0.2323870 -0.2225263
## 2 -0.11077497 -0.3295968 -0.4208728 -0.2275331
## 
## Clustering vector:
##   2   3   4   5   7   9  10  11  13  14  15  16  17  18  19  20  21  22  25  26 
##   1   1   2   1   2   1   1   2   1   1   1   1   1   2   1   1   2   1   2   2 
##  27  28  30  32  33  34  35  37  39  41  42  43  44  46  48  49  50  51  53  54 
##   2   1   2   1   1   1   1   1   1   1   2   1   2   1   2   1   2   1   1   1 
##  55  56  57  58  59  61  62  63  66  67  69  70  72  73  74  75  76  77  78  80 
##   1   1   1   1   1   2   1   2   1   1   1   2   1   1   1   2   1   2   1   1 
##  81  82  84  85  86  87  88  89  90  92  93  94  95  98  99 100 101 102 103 105 
##   2   1   1   1   1   2   2   2   1   1   2   2   1   1   1   1   1   2   2   1 
## 107 110 111 112 115 116 117 122 124 125 128 129 130 131 132 133 134 135 138 139 
##   1   2   1   1   1   1   2   1   1   2   1   2   1   1   1   1   2   2   1   1 
## 140 141 142 143 144 145 147 148 149 150 151 152 155 156 157 159 160 162 163 164 
##   1   1   1   1   1   1   1   1   2   1   2   2   1   1   1   1   1   2   2   1 
## 165 166 167 168 169 171 172 173 175 176 177 178 179 182 183 184 185 186 188 190 
##   1   1   2   1   2   1   2   2   1   1   1   1   1   1   1   2   2   1   1   1 
## 192 194 196 197 198 199 200 201 202 203 204 208 209 210 212 214 215 216 217 218 
##   1   2   1   2   2   1   2   2   1   2   1   1   2   2   1   1   1   2   2   2 
## 219 220 221 222 224 225 226 227 230 232 233 234 237 238 239 240 241 242 244 247 
##   1   2   2   2   2   2   1   2   2   1   2   2   1   2   1   1   2   2   2   1 
## 249 250 251 252 253 254 255 256 257 258 259 260 262 263 268 269 270 271 273 274 
##   1   1   1   1   2   1   2   2   2   1   1   2   2   1   1   1   1   1   2   1 
## 275 276 277 278 279 281 283 287 288 289 290 291 294 295 297 298 301 302 
##   1   2   2   1   2   1   1   1   1   1   1   2   2   1   2   1   2   1 
## 
## Within cluster sum of squares by cluster:
## [1] 1090.1852  623.1766
##  (between_SS / total_SS =  12.9 %)
## 
## Available components:
## 
## [1] "cluster"      "centers"      "totss"        "withinss"     "tot.withinss"
## [6] "betweenss"    "size"         "iter"         "ifault"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{datos\_km}\SpecialCharTok{$}\NormalTok{tot.withinss}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1713.362
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{datos\_km}\SpecialCharTok{$}\NormalTok{withinss}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1090.1852  623.1766
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sum}\NormalTok{(datos\_km}\SpecialCharTok{$}\NormalTok{withinss)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1713.362
\end{verbatim}

Es importante asegurarse de que el algoritmo k-means esté agrupando los
datos de una manera que sea coherente con la estructura real de los
datos. En otras palabras, el objetivo de utilizar k-means no es
simplemente obtener una partición de los datos, sino también garantizar
que los grupos resultantes sean relevantes

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(data2[, }\DecValTok{1}\SpecialCharTok{:}\DecValTok{10}\NormalTok{],}
\AttributeTok{col =}\NormalTok{ datos\_km}\SpecialCharTok{$}\NormalTok{cluster }\SpecialCharTok{+} \DecValTok{1}\NormalTok{,}
\AttributeTok{pch =} \FunctionTok{as.numeric}\NormalTok{(}\FunctionTok{as.factor}\NormalTok{(data2}\SpecialCharTok{$}\NormalTok{diagnosis)))}
\end{Highlighting}
\end{Shaded}

\includegraphics{methods-II_files/figure-latex/unnamed-chunk-63-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{table}\NormalTok{(datos\_km}\SpecialCharTok{$}\NormalTok{cluster, data2}\SpecialCharTok{$}\NormalTok{diagnosis)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    
##     healthy heartDisease
##   1      91           46
##   2      72            9
\end{verbatim}

En algunos casos, puede no estar claro si el algoritmo k-means está
agrupando los datos de una manera que sea consistente con la estructura
real de los datos. Esto puede suceder si los datos presentan una
estructura compleja o si las variables no están adecuadamente
normalizadas. En este caso, es posible que el algoritmo k-means produzca
clústeres que no reflejen la verdadera estructura subyacente de los
datos, ya que está des-balanceado el dataset.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ncluster }\OtherTok{\textless{}{-}} \DecValTok{1}\SpecialCharTok{:}\DecValTok{20}
\NormalTok{distorsion }\OtherTok{\textless{}{-}} \FunctionTok{sapply}\NormalTok{(ncluster,}
\ControlFlowTok{function}\NormalTok{(K) }\FunctionTok{kmeans}\NormalTok{(data2[,}\SpecialCharTok{{-}}\DecValTok{11}\NormalTok{],}
\NormalTok{K, }\AttributeTok{nstart =} \DecValTok{10}\NormalTok{)}\SpecialCharTok{$}\NormalTok{tot.withinss)}

\FunctionTok{plot}\NormalTok{(ncluster,}
\NormalTok{distorsion,}
\AttributeTok{type =} \StringTok{"b"}\NormalTok{,}
\AttributeTok{pch =} \DecValTok{19}\NormalTok{,}
\AttributeTok{xlab =} \StringTok{"K"}\NormalTok{,}
\AttributeTok{ylab =} \StringTok{"Distorsión"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{methods-II_files/figure-latex/unnamed-chunk-64-1.pdf}

\hypertarget{clustering-jeruxe1rquico-agregativo}{%
\subsection{Clustering jerárquico
agregativo}\label{clustering-jeruxe1rquico-agregativo}}

Los métodos jerárquicos agregativos son una técnica de análisis
multivariante que permiten la agrupación de observaciones en clústeres.
Estos métodos se basan en la idea de que las observaciones más similares
deben agruparse juntas y las menos similares deben separarse. En la
práctica, este método comienza con cada observación en su propio grupo
y, a continuación, combinan gradualmente los grupos más similares hasta
que se alcanza un único grupo que contiene todas las instancias u
observaciones. Este proceso de agrupamiento se representa mediante un
dendrograma, que es una representación gráfica de la estructura
jerárquica de los grupos, nuestro caso no mostramos está representación
por la cantidad de datos.~

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data\_NCCo }\OtherTok{\textless{}{-}} \FunctionTok{NbClust}\NormalTok{(data2[,}\SpecialCharTok{{-}}\DecValTok{11}\NormalTok{], }\AttributeTok{method =} \StringTok{"complete"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{methods-II_files/figure-latex/unnamed-chunk-65-1.pdf}

\begin{verbatim}
## *** : The Hubert index is a graphical method of determining the number of clusters.
##                 In the plot of Hubert index, we seek a significant knee that corresponds to a 
##                 significant increase of the value of the measure i.e the significant peak in Hubert
##                 index second differences plot. 
## 
\end{verbatim}

\includegraphics{methods-II_files/figure-latex/unnamed-chunk-65-2.pdf}

\begin{verbatim}
## *** : The D index is a graphical method of determining the number of clusters. 
##                 In the plot of D index, we seek a significant knee (the significant peak in Dindex
##                 second differences plot) that corresponds to a significant increase of the value of
##                 the measure. 
##  
## ******************************************************************* 
## * Among all indices:                                                
## * 11 proposed 2 as the best number of clusters 
## * 1 proposed 3 as the best number of clusters 
## * 1 proposed 4 as the best number of clusters 
## * 3 proposed 6 as the best number of clusters 
## * 5 proposed 7 as the best number of clusters 
## * 1 proposed 13 as the best number of clusters 
## * 2 proposed 15 as the best number of clusters 
## 
##                    ***** Conclusion *****                            
##  
## * According to the majority rule, the best number of clusters is  2 
##  
##  
## *******************************************************************
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data\_NCS }\OtherTok{\textless{}{-}} \FunctionTok{NbClust}\NormalTok{(data2[,}\SpecialCharTok{{-}}\DecValTok{11}\NormalTok{], }\AttributeTok{method =} \StringTok{"single"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in pf(beale, pp, df2): NaNs produced
\end{verbatim}

\includegraphics{methods-II_files/figure-latex/unnamed-chunk-65-3.pdf}

\begin{verbatim}
## *** : The Hubert index is a graphical method of determining the number of clusters.
##                 In the plot of Hubert index, we seek a significant knee that corresponds to a 
##                 significant increase of the value of the measure i.e the significant peak in Hubert
##                 index second differences plot. 
## 
\end{verbatim}

\includegraphics{methods-II_files/figure-latex/unnamed-chunk-65-4.pdf}

\begin{verbatim}
## *** : The D index is a graphical method of determining the number of clusters. 
##                 In the plot of D index, we seek a significant knee (the significant peak in Dindex
##                 second differences plot) that corresponds to a significant increase of the value of
##                 the measure. 
##  
## ******************************************************************* 
## * Among all indices:                                                
## * 8 proposed 2 as the best number of clusters 
## * 3 proposed 3 as the best number of clusters 
## * 1 proposed 6 as the best number of clusters 
## * 10 proposed 8 as the best number of clusters 
## * 2 proposed 9 as the best number of clusters 
## 
##                    ***** Conclusion *****                            
##  
## * According to the majority rule, the best number of clusters is  8 
##  
##  
## *******************************************************************
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data\_NCA }\OtherTok{\textless{}{-}} \FunctionTok{NbClust}\NormalTok{(data2[,}\SpecialCharTok{{-}}\DecValTok{11}\NormalTok{], }\AttributeTok{method =} \StringTok{"average"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in pf(beale, pp, df2): NaNs produced
\end{verbatim}

\includegraphics{methods-II_files/figure-latex/unnamed-chunk-65-5.pdf}

\begin{verbatim}
## *** : The Hubert index is a graphical method of determining the number of clusters.
##                 In the plot of Hubert index, we seek a significant knee that corresponds to a 
##                 significant increase of the value of the measure i.e the significant peak in Hubert
##                 index second differences plot. 
## 
\end{verbatim}

\includegraphics{methods-II_files/figure-latex/unnamed-chunk-65-6.pdf}

\begin{verbatim}
## *** : The D index is a graphical method of determining the number of clusters. 
##                 In the plot of D index, we seek a significant knee (the significant peak in Dindex
##                 second differences plot) that corresponds to a significant increase of the value of
##                 the measure. 
##  
## ******************************************************************* 
## * Among all indices:                                                
## * 9 proposed 2 as the best number of clusters 
## * 1 proposed 3 as the best number of clusters 
## * 4 proposed 5 as the best number of clusters 
## * 3 proposed 10 as the best number of clusters 
## * 1 proposed 12 as the best number of clusters 
## * 1 proposed 13 as the best number of clusters 
## * 3 proposed 14 as the best number of clusters 
## * 2 proposed 15 as the best number of clusters 
## 
##                    ***** Conclusion *****                            
##  
## * According to the majority rule, the best number of clusters is  2 
##  
##  
## *******************************************************************
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data\_NCCe }\OtherTok{\textless{}{-}} \FunctionTok{NbClust}\NormalTok{(data2[,}\SpecialCharTok{{-}}\DecValTok{11}\NormalTok{], }\AttributeTok{method =} \StringTok{"centroid"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in pf(beale, pp, df2): NaNs produced
\end{verbatim}

\includegraphics{methods-II_files/figure-latex/unnamed-chunk-65-7.pdf}

\begin{verbatim}
## *** : The Hubert index is a graphical method of determining the number of clusters.
##                 In the plot of Hubert index, we seek a significant knee that corresponds to a 
##                 significant increase of the value of the measure i.e the significant peak in Hubert
##                 index second differences plot. 
## 
\end{verbatim}

\includegraphics{methods-II_files/figure-latex/unnamed-chunk-65-8.pdf}

\begin{verbatim}
## *** : The D index is a graphical method of determining the number of clusters. 
##                 In the plot of D index, we seek a significant knee (the significant peak in Dindex
##                 second differences plot) that corresponds to a significant increase of the value of
##                 the measure. 
##  
## ******************************************************************* 
## * Among all indices:                                                
## * 9 proposed 2 as the best number of clusters 
## * 4 proposed 3 as the best number of clusters 
## * 1 proposed 4 as the best number of clusters 
## * 1 proposed 5 as the best number of clusters 
## * 2 proposed 11 as the best number of clusters 
## * 5 proposed 12 as the best number of clusters 
## * 2 proposed 15 as the best number of clusters 
## 
##                    ***** Conclusion *****                            
##  
## * According to the majority rule, the best number of clusters is  2 
##  
##  
## *******************************************************************
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#data\_NCA}
\NormalTok{data\_NCA}\SpecialCharTok{$}\NormalTok{Best.partition}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   2   3   4   5   7   9  10  11  13  14  15  16  17  18  19  20  21  22  25  26 
##   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1 
##  27  28  30  32  33  34  35  37  39  41  42  43  44  46  48  49  50  51  53  54 
##   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1 
##  55  56  57  58  59  61  62  63  66  67  69  70  72  73  74  75  76  77  78  80 
##   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1 
##  81  82  84  85  86  87  88  89  90  92  93  94  95  98  99 100 101 102 103 105 
##   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1 
## 107 110 111 112 115 116 117 122 124 125 128 129 130 131 132 133 134 135 138 139 
##   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1 
## 140 141 142 143 144 145 147 148 149 150 151 152 155 156 157 159 160 162 163 164 
##   1   1   1   1   1   1   1   1   1   1   1   2   1   1   1   1   1   1   1   1 
## 165 166 167 168 169 171 172 173 175 176 177 178 179 182 183 184 185 186 188 190 
##   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1 
## 192 194 196 197 198 199 200 201 202 203 204 208 209 210 212 214 215 216 217 218 
##   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1 
## 219 220 221 222 224 225 226 227 230 232 233 234 237 238 239 240 241 242 244 247 
##   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1 
## 249 250 251 252 253 254 255 256 257 258 259 260 262 263 268 269 270 271 273 274 
##   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1 
## 275 276 277 278 279 281 283 287 288 289 290 291 294 295 297 298 301 302 
##   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1
\end{verbatim}

El mejor cluster identifica que el dataset presenta sesgo hacia una
variable en particular.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data\_pca }\OtherTok{\textless{}{-}} \FunctionTok{prcomp}\NormalTok{(data2[,}\SpecialCharTok{{-}}\DecValTok{11}\NormalTok{])}
\NormalTok{Grupo }\OtherTok{\textless{}{-}} \FunctionTok{as.factor}\NormalTok{(}
\NormalTok{data\_NCA}\SpecialCharTok{$}\NormalTok{Best.partition}
\NormalTok{)}
\FunctionTok{ggplot}\NormalTok{(}\FunctionTok{as.data.frame}\NormalTok{(data\_pca}\SpecialCharTok{$}\NormalTok{x),}
\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ PC1, }\AttributeTok{y =}\NormalTok{ PC2, }\AttributeTok{color =}\NormalTok{ Grupo,}
\AttributeTok{label =} \FunctionTok{rownames}\NormalTok{(data2))) }\SpecialCharTok{+}
\FunctionTok{geom\_hline}\NormalTok{(}\AttributeTok{yintercept =} \DecValTok{0}\NormalTok{, }\AttributeTok{lty =} \DecValTok{2}\NormalTok{) }\SpecialCharTok{+}
\FunctionTok{geom\_vline}\NormalTok{(}\AttributeTok{xintercept =} \DecValTok{0}\NormalTok{, }\AttributeTok{lty =} \DecValTok{2}\NormalTok{) }\SpecialCharTok{+}
\FunctionTok{geom\_text}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{methods-II_files/figure-latex/unnamed-chunk-67-1.pdf}

Básicamente está realizando un solo grupo. La técnica funcionaría mejor
si balanceamos los datos.

\hypertarget{bibliografuxeda}{%
\section{Bibliografía}\label{bibliografuxeda}}

{[}1{]} W. Larry, All of Statistics, 1st ed.~Springer Science, 2004.
{[}2{]} R Core Team, `R: A Language and Environment for Statistical
Computing'. Vienna, Austria, 2018. {[}Online{]}. Available:
\url{https://www.R-project.org/} {[}3{]} Rs. Team, `RStudio: Integrated
Development Environment for R'. RStudio, Inc., 2022. {[}4{]} Higueras.
H. Manuel, Notas de Clase. 2022. {[}5{]} E. Brian, H. Torsten, An
Introduction to Applied Multivariate Analysis with R, 1st ed.~Springer
Science, 2011. {[}6{]} P. Daniel, Análisis de Datos Multivariantes,
2014.

\end{document}
